### ISSUE TITLE
Can't access desmos with tmkms

### ISSUE THREAD

**Issue by westaking** [desmos-labs/desmos#107]
## Bug description
tmkms cannot access desmos v0.3.0 for validator
**desmos v0.2.0** worked fine with **no problems with tmkms.**

The following error occurs:

tmkms:
**cryptographic error**
![desmosd](https://user-images.githubusercontent.com/52248090/75739555-80505c00-5d48-11ea-9ab0-a48fa179e2a1.png)

desmos v0.3.0:
![desmos2](https://user-images.githubusercontent.com/52248090/75739634-c1e10700-5d48-11ea-92d6-f0390fa56f59.png)

## Steps to reproduce
 
Set priv_validator_laddr in desmos config.toml for tmkms.

## Expected behavior

tmkms should be connected to desmos 0.3.0 for block signing.

**Comment by RiccardoM** [comment]
Hi @westaking, thanks for the report. 

Have you made sure you migrated your keys by executing the following command before starting the node? 

```bash
desmoscli keys migrate
```

From version `0.3.0` the keys are handled in a different way and they should be migrated before starting the updated node. Please refer to the following links: 

* Upgrade your keys: https://docs.desmos.network/migrations/v0.3.0.html#migrate-your-keys
* Validator update guide: https://primer.desmos.network/phase-3/challenges/update-node.html#keys-migration-required

**Comment by westaking** [comment]
Yes, I did migrate keys.
desmos 0.3.0 works fine without tmkms.
But desmos throws an error with tmkms.

**Comment by kwunyeung** [comment]
Should not be related to the key migration. The `keys migrate` command migrates the keys in the keybase but not the validator key. Have to confirm if this is bug on `Tendermint v0.33`.

**Comment by RiccardoM** [comment]
This is a problem with `tmkms` by Iqlusion. The bug is discussed further here: iqlusioninc/tmkms#24

**Comment by zmanian** [comment]
fixed on kms master
https://github.com/iqlusioninc/tmkms/pull/58

**Comment by RiccardoM** [comment]
westaking Please try installing TMKS version v0.8.0 and let us know if that's fixed. I will close this in the meantime.
