### ISSUE TITLE
Slashing index_offset is not correct after export with --for-zero-height

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#108]
The validators are not being jailed after the defined `signed_blocks_window`. Here are the parameters on `morpheus-3000`.

```json
{
  "height": "33699",
  "result": {
    "signed_blocks_window": "720",
    "min_signed_per_window": "0.050000000000000000",
    "downtime_jail_duration": "600000000000",
    "slash_fraction_double_sign": "0.050000000000000000",
    "slash_fraction_downtime": "0.010000000000000000"
  }
}
```
Which means if a validator missed 95% of 720 blocks (684 blocks ~ 1hr), it will be jailed and unbonded.

However, many validators not validating are still bonded. This is due to the wrong signing-info, for example,

```json
{
  "address": "desmosvalcons1xd7zavv738jxf2th343ka7ytfvhea55908r9nl",
  "start_height": "34471",
  "index_offset": "85705",
  "jailed_until": "2020-02-26T06:31:42.069077155Z",
  "tombstoned": false,
  "missed_blocks_counter": "720"
}
```
The `morpheus-1001` app state was exported with `--for-zero-height` and it is expected to reset the start height to zero with a correct `index_offset`.

https://github.com/desmos-labs/desmos/blob/master/app/export.go#L167

Clearly this is not the case, we have to wait till height 120,896 too see it being jailed.

**Comment by RiccardoM** [comment]
@kwunyeung After taking a look at this, I've noticed that the actual jailing of the validator happens before that point. In particular, at [line 152](https://github.com/desmos-labs/desmos/blob/master/app/export.go#L152) we can see: 

```golang
if applyWhiteList && !whiteListMap[addr.String()] {
	validator.Jailed = true
}
```

Taking a look at the usage of the `IndexOffset` value, from the CosmosSDK we can read: 

```golang
IndexOffset   int64   `json:"index_offset" yaml:"index_offset"`    // index offset into signed block bit array
```

So, I think that offset is correctly exported and should not be changed if the state is exported for zero height, as we also can see inside the Cosmos [prepForZeroHeightGenesis implementation](https://github.com/cosmos/cosmos-sdk/blob/14e3aa126586160d0603c996869683b3892c60cb/simapp/export.go#L159)
