### ISSUE TITLE
Export with --height is not working

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#109]
```
desmosd export --height 700000 --home morpheus-1001/ > export-1001.json
```
This is export the app state at height 700000. However it doesn't work and gives me this error.

```
ERROR: error exporting state: failed to load Store: wanted to load target 700000 but only found up to 0
```
`morpheus-1001` stopped after 713,000 but can't export any height other than the latest state.

**Comment by RiccardoM** [comment]
This has not verified on later versions of `morpheus` as far as I know, so I'm going to close it until it refaces again.
