### ISSUE TITLE
Study the possibility to change the RESTful API to GraphQL

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#11]
The current Cosmos SDK expose a RESTful API. Although we target to have a fully standalone WASM client, we should keep the LCD for other use cases. The LCD is a RESTful API with a lot of specific endpoints. We can study if there are possibilities to change this to be GraphQL which can reduce the number of queries when using RESTful API. If this works, we can contribute back to the SDK.

https://github.com/graphql-go/graphql

**Comment by RiccardoM** [comment]
Closing this in favor of the system described inside #60
