### ISSUE TITLE
Integrate CosmWasm

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#115]
In order to allow custom applications to implement their features the best way possible without having to fork the Desmos chain, I think we should start taking a look at [CosmWasm](https://github.com/confio/cosmwasm). 

This Cosmos module, developed by Ethan Frey, allows anyone to write smart contracts that can later run on the chain itself. 

This could be particularly useful for example when integrating custom posts reporting logics as described inside #50.

**Comment by kwunyeung** [comment]
I was in their community call today. The current design of CosmWASM is to have its own state for each smart contract. I think this is very good when we have different dapps running on Desmos. Even for the flagging issue, different dapps can keep their states whether a post should be visible or not. I have also asked the upgradability of the contracts and they are [tracking this feature here](https://github.com/confio/cosmwasm/issues/77).

**Comment by RiccardoM** [comment]
> different dapps can keep their states

This is great!

**Comment by bragaz** [comment]
This should be doable now, I can follow the [wasmd](https://github.com/CosmWasm/wasmd) example which is already compatible with stargate.
