### ISSUE TITLE
Update the post creation CLI command

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#117]
## Feature description 
With #113 we've allowed to create posts with an empty message when there are some medias attached to them. This has caused the CLI command in that case to be very unnatural to use.

Currently the command is
```
desmoscli tx posts create <subspace> <message> <allows-comments> --flags
```

Which results (when an empty message is specified) to be: 
```
desmoscli tx posts create "subspace" "" true/false --flags
```

This is very unnatural for the users and we should probably fix it. 

## Implementation proposal
What I suggest to do is improve the posting command by making the message an optional flag instead of a required argument: 

```
desmoscli tx posts create <subspace> <allows-comments> \
  --message="My message"
  --flags
```

Of course, with this implementation inside the CLI tx command handler we need to check that the message is not empty when the medias are, and vice-versa, to make sure that at least one between the message and the medias are specified.

**Comment by kwunyeung** [comment]
How about this? 

Making the `cobra.MinimumArgs` to `1`. Only `<subspace>` is mandatory. Keep `<message>` as an argument but optional. Put `--allow-comments` as a flag and its default is `true` if not specified. The command can be like this.

```
desmoscli tx posts create <subspace> "My message" \
  --allow-comments=false
  --flags
```
I feel putting the `<message>` as an argument in the command line is more straightforward.

**Comment by RiccardoM** [comment]
@kwunyeung Love this proposal! Didn't remember `viper` allows for optional arguments

**Comment by bragaz** [comment]
Kwun proposal is perfect!
