### ISSUE TITLE
Implement media tagging 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#118]
## Feature description 
Currently, when creating a media the user can specified it's `URI` and `MimeType`. In order to better support media sharing (particularly images) on a wide range of social networks, we should implement media tagging. Thanks to this features, users will be able to tag other users on a particular image to make sure they are someone recognizes when that image is viewed. 

## Implementation proposal
In order to implement media tagging, the following changes should be made. 

### Update he PostMedia type
First of all, we need to update the `PostMedia` type to be: 

```golang
type PostMedia struct {
	URI      string           `json:"uri"`
	MimeType string           `json:"mime_type"`
        Tags     []sdk.AccAddress `json:"tags"`     // Contains the list of all the tagged users
}
```

### Update the CLI and REST commands
Then we need to update the CLI and REST commands to allow tagging. The most particular one will be the CLI one. I think the `--media` flag can be changed to something like:

```
--media "<URI>,<MimeType>,<Tags...>
```

So an example could be

```
--media "https://example.com,image/jpeg,desmos1p7c8h59nrc8e5hxvgvu2g7tpp0xwn4mzevzgg7,desmos1p7ad878nealg249qkkdl9ldxrllst23lklngcx
```

What are your thoughts on this @bragaz @kwunyeung?

**Comment by bragaz** [comment]
I could go with this one, what do you think? @RiccardoM
