### ISSUE TITLE
Improve storing and reading 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#125]
## Context
While storing and reading posts, poll answers, reactions and other on-chain data, we are currently doing it in a very naive method: 

- when reading data, we iterate over all the set to find the data that we most like
- when writing data, we replace the entire existing slice with a new one to which we have added the new element 

While this methods surely work, in the latest transactions they are now showing some weak points. As reading and writing cost gas while performing a transaction, in fact, some recent transactions have been failing due to gas shortage (you can see it even [here](https://morpheus.desmos.network/transactions/952E999BA51BB32F20AF079F831F285D2609E006AB01DF367547F701FF5B3528) and [here](https://morpheus.desmos.network/transactions/FC85D7C0F8FAA06F1F4FD835A753069E80EB239649C9265777791058CC50F69A)). 

In order to make sure that our transactions do not cost too much, we should probably improve how we read and write data. 

## Possible solutions
Below, there are some possible solutions I've thought that might help us out with these problems. 

### Reading
When finding a specific post, reaction or similar inside a slice, instead of iterating over all the slice itself we should probably do it using a more efficient algorithm. An example could be the [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm) algorithm, which is already implemented inside Go using the [`sort.Search method`](https://flaviocopes.com/golang-algorithms-binary-search/).

Also, another idea to further improve the reading time could be the one to keep the data sorted when saving it. This way the search might be faster.

### Writing 
Currently I have no idea on how we could improve the writing speed. 

## Conclusion
I'd like @bragaz and @kwunyeung ideas on these approaches.

**Comment by kwunyeung** [comment]
Should we try using `RocksDB` in the next testnet? Seems pretty fast, developed by FB and they are using it. We only have to add one more build tag.

**Comment by RiccardoM** [comment]
@kwunyeung Can you write here the buildtag that needs to be added? We might want to test it out

**Comment by bragaz** [comment]
We should also take a look to the future transactions with the new ID improvements in order to see if there are problems with gas shortage yet.
