### ISSUE TITLE
Update Cosmos to v0.38.3

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#127]
Yesterday AIB shared with the cosmos community the recent discover of a [high-severity security vulnerability that impacts all versions of Tendermint](https://forum.cosmos.network/t/cosmos-mainnet-security-advisory-lavender/3511).
To fix this issue, they will release a new version of tendermint and cosmos sdk today at 14:00 UTC.
We need to upgrade to this version in order to fix this security problem.

**Comment by RiccardoM** [comment]
What should be done is start from the current `0.3.0` release, update the Tendermint version there with the most recent one, and then release a `0.3.1` if possible. 

Then all the nodes should upgrade as soon as possible.

**Comment by RiccardoM** [comment]
Closes with #123
