### ISSUE TITLE
Improve how posts are returned to the clients

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#140]
> Taken from a [conversation](https://github.com/desmos-labs/desmos/pull/136#issuecomment-618424093) which happened inside #136

While taking a look at the code, I thought that maybe we want to improve how the reactions list is returned to the user when he asks for a posts list of a post details. Currently the returned object is 

```golang
type PostQueryResponse struct {
	Post
	PollAnswers []UserAnswer  `json:"poll_answers,omitempty"`
	Reactions   PostReactions `json:"reactions"`
	Children    PostIDs       `json:"children"`
}
```

What if we make it as follows?

```golang
type PostQueryResponse struct {
	Post
	PollAnswers []UserAnswer           `json:"poll_answers,omitempty"`
	Reactions   PostReactionsResponses `json:"reactions"`
	Children    PostIDs                `json:"children"`
}
```

Each object of `PostReactionsResponses` should be defined as:

```golang
type PostReactionsResponse struct { 
	Value string         `json:"value"`
	Code string          `json:"code"`
 	User sdk.AccAddress  `json:"user"`
}
```

This way I think the client could handle the reaction better having both the code and the value (emoji or URI). What do you think @bragaz?

**Comment by RiccardoM** [comment]
@bragaz [said](https://github.com/desmos-labs/desmos/pull/136#issuecomment-618466029): 

> Currently the `PostReaction` type has the following signature:
> 
>  ```golang
>  // PostReaction is a struct of a user reaction to a post
>  type PostReaction struct {
> 	Owner sdk.AccAddress `json:"owner"` // Creator that has created the reaction
> 	Value string         `json:"value"` // PostReaction of the reaction
> }
> ```
> 
> So in order to do that we should firstly get all the registered reaction (with the current `ListReaction(ctx sdk.Context)`) and then iterate over them to get the corresponded value associated with the shortcode of the `postReaction` which sounds crazy and would cost a lot of gas probably.
> 
> I think that a way to simplify the life of clients could be improve our actual `queryRegisteredReactions` by returning something like a `RegisteredReactionResponse`with which they can better search for the value associated to the shortcode instead of the simple `registeredReactions` slice.

**Comment by RiccardoM** [comment]
@bragaz I'd like to break down your observations into multiple points. 

> in order to do that we should firstly get all the registered reaction (with the current `ListReaction(ctx sdk.Context)`)

Since we save registered reactions inside the store associating to them a key which is composed of the reaction shortcode and the subspace for which the reaction is registered, what we could do is creating a new method which might look like the following: 

```golang
func (keeper Keeper) GetRegisteredReaction(ctx sdk.Context, shortCode string, subspace string) Reaction {
}
```

This should return the reaction (if exists) in approximately `O(1)` which is pretty fast. 


> would cost a lot of gas probably

While this is generically not good, we need to consider gas only when talking about operations that are performed **while executing transactions**. In this case while simply querying the state no gas is required and all the operations a free of charge.

> I think that a way to simplify the life of clients could be improve our actual `queryRegisteredReactions` by returning something like a `RegisteredReactionResponse`with which they can better search for the value associated to the shortcode instead of the simple `registeredReactions` slice.

We don't need to edit that. The `registeredReactions` slice already contains all `Reaction` object which have the shortcode and the value inside, as well as other data such as who has registered the reaction and the subspace inside which it is valid.

**Comment by RiccardoM** [comment]
I've just noticed we already have the method I proposed, just named differently. It's `DoesReactionForShortCodeExist`

**Comment by bragaz** [comment]
Oh I see. I missing the fact that queries don't need any gas and so my entire think can be reformulated.
So now you can use `DoesReactionForShortCodeExist` to get the registered reaction associated with the `postReaction` shortcode and get the `value` we need.
