### ISSUE TITLE
Proposal for a better Continous Integration

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#143]
## Context
With release `v0.4.0`, we've had a couple of issues that resulted in a multiple tag of the same release and a necessity of re-creating the chain from scratch during internal tests. After having reflected on what caused these types of problems, I came to the conclusion that the causes where the following: 

- The milestone was very big. [Milestone 0.4.0](https://github.com/desmos-labs/desmos/milestone/4?closed=1) had 12 issues opened inside it. This has since now been the largest milestone ever opened. 

- Due to the highest number of changes made and the short time available, the reviews of the different pull requests were not made properly.

- Bad PRs reviews lead to a series of bug mistakenly being merged into `master`, supported by the fact that the same reviews did not highlight missing or wrong tests.

- This inevitably caused the malfunctioning of the chain after the upgrade. 

## Better CI proposal
In order to make sure the above mistakes are not going to be made again, I suggest we start following from now on a new way of doing Continous Integration. 

I really think that **15 days sprints** will be a good balance between the need of integrating new features and the need of time to review such features. What I propose is: 

- Create milestones with few elements (3 to 5 issues) inside. 

- Make sure each milestone can be closed in 15 days or less. 

- Make sure each issue inside the milestone had the proper time to be implemented, tested and reviewed without the need of rushing any of these steps. 

This method should allow us to publish a new version of Desmos every 15 days, making sure it's stable and ready to be released. 

### Validators updates
Currently I'm currently not sure whether we want to ask our validators to update once per 15 days, or we should keep one update per month. 

Even if we choose the latter, this 15 days proposal will have no effect on them, we will simply require them to update to a new version skipping the one in between. 

## Conclusion
What do you guys think about this proposal? @kwunyeung @bragaz

**Comment by bragaz** [comment]
As I already told you on the last saturday I think this would be good enough to let us doing better tests and PR reviews. So I agree and I think we can try this way of working starting from this milestone.

**Comment by kwunyeung** [comment]
Making it two-week sprint is reasonable. Asking validators update more frequently is acceptable and this is how we can keep their engagement in the community. As long as the update doesn't include as major state change and is not consensus breaking, the workload of the upgrade is minimal. I'm good for this.
