### ISSUE TITLE
Improve reactions events

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#144]
## Context
Currently when a user adds or removes a reaction to a post, the following event is emitted: 

```golang
sdk.NewEvent(
	types.EventTypePostReactionAdded,
	sdk.NewAttribute(types.AttributeKeyPostID, msg.PostID.String()),
	sdk.NewAttribute(types.AttributeKeyPostReactionOwner, msg.User.String()),
	sdk.NewAttribute(types.AttributeKeyReactionShortCode, reactionValue),
)
```

As we can see, the event contains only the associated short code of the reaction that is added to the post. While this might be ok, it presents two problems: 

1. If the user adds ":smile:" as a reaction, the event will instead contain `:smile:`, which might be confusing to watch from an external point of view cause it doesn't tell where that code comes from and where the value has gone. 

2. If the user needs to have both the added value as well as the added shortcode, he will need to parse the event and the message, which is pretty strange. 

## Solution
In order to improve the usability of such events, what I suggest we should do is adding another attribute to both the event emitted when processing `MsgAddPostReaction` and the one emitted when processing `MsgRemovePostReaction` so that both contain: 

- the `shortcode` of the added reaction
- the `value` (either emoji or URI) of the added reaction. This can be read from the store (if already registered) or from the value (if an emoji).

**Comment by kwunyeung** [comment]
I will good for the explorer to show the transactions as well.
