### ISSUE TITLE
Query profile command with address can't be used

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#155]
The code here 

https://github.com/desmos-labs/desmos/blob/master/x/profile/client/cli/query.go#L33

will make the subcommand become 
```sh
desmoscli q profile [address
```

**Comment by RiccardoM** [comment]
I think the solution is as as simple as changing from `[address or moniker]` to `[address_or_moniker]`

**Comment by bragaz** [comment]
I will fixi it today
