### ISSUE TITLE
Missing shortcodes in emojis list

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#164]
## Bug description
While working on issue #126 I've found out that some emojis has no related shortcodes.
This could lead to possibile errors when some users will try to use them.
## Steps to reproduce
 
- Switching to my `benchmarks-tests-impl` branch
- Uncomment the `randomMapKey` `RandomPostReaction` functions
- Uncomment lines 171
- Use the `reaction` variable inside the `SavePostReaction` func
- Remove from line 174 to 179
- Run the test

## Expected behavior
```golang
panic: runtime error: index out of range [0] with length 0
```

**Comment by RiccardoM** [comment]
I should have fixed this inside 6eaba8e by: 

1. Updating the `Go-Emoji-Utils` library to also have an `emojis.EmojisList` variable that represents the Emojis as a slice. 
2. Getting a random emoji from that list.

We can leave this issue open. It should close automatically once #165 is merged.
