### ISSUE TITLE
Non deterministic post id creation

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#17]
I might be completely wrong, but I think that currently inside the `handleMsgCreatePost` there is a non deterministic operation, which is 

```golang
post := types.Post{
    ID:            xid.New().String(),
}
```

Seeing the code inside the `xid.New()` method, it uses the current time to generate a globally unique identifier. If this code runs on multiple nodes, it won't produce the same effect. 

I personally think we have two options: 

1. Find a way to change how this id is generated, making it deterministic
2. Allow clients to specify it and just check for its validity (using a regex) and uniqueness

I think the second option is the best one, and would also mean that we can simplify the `MsgCreatePost` by asking the client to send a full `Post` object and later changing its likes number to `0`.

**Comment by RiccardoM** [comment]
This seems to happen also inside the `handleMsgLike`:

```golang
like := types.Like{
    ID:            xid.New().String(),
}
```

And inside `handleMsgCreateSession`

```golang
session := types.Session{
    ID:            xid.New().String(),
}
```

**Comment by kwunyeung** [comment]
Why you think this ID should be deterministic?

**Comment by RiccardoM** [comment]
@kwunyeung Let's consider the situation in which we have two different nodes, A and B.

The TX is processed by both nodes to update their respective statuses. While processing the MsgCreatePost message, this happens:

- on node A, the new post's ID assumes value X
- on node B, the new post's ID assumes value Y

After creating the post, the client then asks to both nodes for the list of all posts. What will he get are two different lists:

- from node A he will get a list containing a post with ID X
- from node B he will get a list containing a post with ID Y

What ID should it use when liking the post now? Should it use X or Y?

This obviously gets more and more complicated as new nodes are taking in consideration. 

As far as I've understood the Handler is called on each node to update the local status, and thus the handler behavior should be 100% deterministic to make sure each node has the same status at each given point in time.
With this random ID generation we cannot guarantee it and thus we might run into conflicting statuses problems later in time.

**Comment by kwunyeung** [comment]
Oops! My bad. Yes it has to be deterministic. Let's change it to an incremental ID like proposal ID and sequence before we get a solution on verifiable random number.
