### ISSUE TITLE
Bring back the upgrade module

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#174]
Taken from #142 

> Currently inside Desmos we were not making usage of the governance and upgrade modules. The first one was not used at all, while the second one was plugged in a couple of versions ago but never properly tested. 

> I've decided to remove them temporary inside `v0.4.0` to avoid having any problem inside our testnets, but we should definitely bring them back in the future.

With this issue I want to track the bringing back of the `upgrade` module.

**Comment by RiccardoM** [comment]
Note that when bringing back this module, a micro test should also be performed locally in order to test the upgrading feature, and such test steps should be provided to everyone that might want to try it out as well.

**Comment by RiccardoM** [comment]
After discussing with @bragaz, we've found out that the `x/upgrade` module has some problems currently: 

- It will not work unless the nodes run the binary with the `--prune=nothing` option that makes them archives. This problem is tracked inside [issue #5746 inside Cosmos repository](https://github.com/cosmos/cosmos-sdk/issues/5746). 

- Currently there are still some minor bugs, especially with transactions commands. This is tracked inside [issue #6284](https://github.com/cosmos/cosmos-sdk/issues/6284) and [PR #6285](https://github.com/cosmos/cosmos-sdk/pull/6285). 

It looks like the overall module has some issues open related to it ([see here](https://github.com/cosmos/cosmos-sdk/issues?q=is%3Aissue+is%3Aopen+label%3Ax%2Fupgrade+) and it's tarted to be released inside Cosmos `0.39`. 

That being said, I'm going to put this issue on hold until those things have been resolved.

**Comment by anilCSE** [comment]
@RiccardoM I have been testing the upgrade module from quite a time now. We have tested it on multiple testnets. Meta issue and test scripts need to be handled, but they are not blockers. The critical issue is with pruning. 0.39 should have a fix for this issue. I can help in testing the features

**Comment by bragaz** [comment]
@anilCSE Is There a date set for the `0.39`?

**Comment by RiccardoM** [comment]
Hi @anilCSE, thanks for your willingness in helping us. I've tried implementing the `upgrade` module inside our code (this has been done inside the `riccardo/upgrade-module` branch). Unluckily, I got the following errros when trying to create a proposal: 
```
$ desmoscli tx gov submit-proposal software-upgrade "test" --upgrade-height=100 --from jack
ERROR: invalid proposal content: proposal title cannot be blank [cosmos/cosmos-sdk@v0.38.5/x/gov/types/content.go:38]
```

```
$ desmoscli tx gov submit-proposal software-upgrade "test" --upgrade-height=100 --from jack --upgrade-info --help
ERROR: unknown flag: --upgrade-info
```

Do you have any idea why this might happen? The Cosmos SDK version we're using is `v0.38.5`

**Comment by anilCSE** [comment]
You just need to add "title" flag, it's a mandatory flag for this command.
`desmoscli tx gov submit-proposal software-upgrade "test" --title "test software upgrade proposal" --description "something about the proposal here" --upgrade-height=100 --from jack`

Then `name` and `title` looks bit ambiguous but they have different functionality here. 
`name` suggests the upgrade-name and it will be used inside `upgrade-hanlder` and should be an unique active proposal name. Title is meta for the proposal.

**Comment by RiccardoM** [comment]
@anilCSE Thank you very much! :pray: Do you by any chance have the reference to some piece of code that performs some migrations inside an upgrade handler that you used in the past? I would like to understand how to handle possibly breaking changes migrations

**Comment by anilCSE** [comment]
@RiccardoM you can check this PRs for some example upgrade handlers: 
https://github.com/regen-network/regen-ledger/pull/98 
https://github.com/ovrclk/akash/pull/598

These are just example handlers, we don't use them to mint/update stake in general cases. Most of the times the handler will be empty as in: https://github.com/ovrclk/akash/pull/561/files

We can use the handler to update `params` as well.

**Comment by RiccardoM** [comment]
@anilCSE Thank you! Do you by any chance have also some upgrade proposals examples that allow to auto-download the new binary?

**Comment by anilCSE** [comment]
> @anilCSE Thank you! Do you by any chance have also some upgrade proposals examples that allow to auto-download the new binary?

I didn't try that but you can keep the binary information inside `info` object I guess and `cosmosd` can take care of the upgrade process automatically.

**Comment by RiccardoM** [comment]
@anilCSE I've tried setting up `cosmosd` to properly handle the upgrades, and I've set `DAEMON_RESTART_AFTER_UPGRADE=on`. When the upgrade height is reached, the new binary is started and I get the following: 

```
E[2020-07-20|15:40:34.636] BINARY UPDATED BEFORE TRIGGER! UPGRADE "test" - in binary but not executed on chain module=main 
panic: BINARY UPDATED BEFORE TRIGGER! UPGRADE "test" - in binary but not executed on chain
```

Do you have any idea why that might happen?

**Comment by anilCSE** [comment]
Are you running multiple validators? Looks like you stopped old binary before the upgrade height. Or else, you might be facing issues with `pruning`. If you are using 0.38.x, make sure to use `pruning: nothing` and otherwise you will face state load issues for upgrades(https://github.com/cosmos/cosmos-sdk/issues/5746)

**Comment by RiccardoM** [comment]
@anilCSE I was running a local, single validator node chain. You were right, it was due to me starting the node without specifying `--pruning nothing`. After setting it the problem was solved and the test upgrade was succesful, Thank you very much! :pray:
