### ISSUE TITLE
Implement the evidence module

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#189]
In an effort of fixing #141, we should try implementing the `evidence` module again.

This should be done for a new `v0.5.3` version, which base code should be `v0.5.2` one. So: 

1. Checkout `tags/v0.5.2`. 
2. Create a new branch `versions/0.5.3` from such tag. 
3. Implement the changes on such branch.

**Comment by bragaz** [comment]
I've tried to re-implement the evidence module but it seems like nothing changed.
I've tried to run it on my validator. Our last resort is to ask into the cosmos discord, I can ask there tomorrow.
Also I've found this: https://www.gitmemory.com/issue/cosmos/cosmos-sdk/4012/480477596
but it's not our case, can you confirm?

**Comment by RiccardoM** [comment]
@bragaz I think in our case it is related to the slashing, but I'm not sure if for jailing or what. Maybe @kwunyeung can answer better.

**Comment by bragaz** [comment]
In the meantime I've asked here: [cosmos/cosmos-sdk#6070](https://github.com/cosmos/cosmos-sdk/issues/6070)

**Comment by RiccardoM** [comment]
I'm going to close this issue as well as milestone `Version 0.5.3` as we've seen that this did not solve the problem
