### ISSUE TITLE
Remove all the internal folders

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#197]
Looking at the [Cosmos codebase](https://github.com/cosmos/cosmos-sdk) it looks like they are finally getting rid of all the `/internal` folders. I think we should definitely follow this path as well, removing also the `alias.go` files.

**Comment by bragaz** [comment]
I agree. When we close the actual opened PR's I could handle this.

**Comment by RiccardoM** [comment]
> I agree. When we close the actual opened PRs I could handle this.

I would target it for `v0.9.0`, closing `v0.8.0` first.

**Comment by bragaz** [comment]
I noticed while doing this that `alias.go` files have not been removed yet cause aliases are used inside `app.go`.
Should we remove them already by directly including imports from modules' keepers and other things?

**Comment by RiccardoM** [comment]
> I noticed while doing this that `alias.go` files have not been removed yet cause aliases are used inside `app.go`.
> Should we remove them already by directly including imports from modules' keepers and other things?
> Probably we should stay aligned with how `v0.38.4` files are managed.

I think that if we remove the `internal` folder, then we can have different imports such as `poststypes github.com/desmos-labs/desmos/x/posts/types` and `postskeeper github.com/desmos-labs/desmos/x/posts/keeper`. 

For the post module, I would avoid deleting the `alias` inside the `types` folder since it makes it more organized, but I would remove the one inside the `x/posts` folder.
