### ISSUE TITLE
Replace SetupTestInput methods with test suits 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#198]
Looking at the [Cosmos SDK codebase](https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/keeper/keeper_test.go#L60) it looks like they've swapped all the `SetupTestInput` methods for easier-to-understand [`testify.Suite`](https://github.com/stretchr/testify/blob/master/suite/suite.go#L22) implementations. 

I think we should adopt the same strategy, making the tests easier to setup and maintain.

**Comment by bragaz** [comment]
I will take a look at it soon!

**Comment by RiccardoM** [comment]
> I will take a look at it soon!

Don't rush it, I would target it for `v0.9.0`, focusing on closing `v0.8.0` first.
