### ISSUE TITLE
Rename the x/profile module to x/profiles

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#200]
Currently all the modules have a plural name if they deal with multiple items of that type (eg. `posts`, `reports`). I think that we should rename the `profile` one the same way making it `profiles` to make it consistent.

**Comment by bragaz** [comment]
done [here](https://github.com/desmos-labs/desmos/commit/fd64bf9289c55f54cd2987ac3dc0a79580979443)
