### ISSUE TITLE
Edit post should allow users to edit media and poll

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#202]
## Feature description 

Currently `MsgEditPost` only accept updating the text message. 

https://github.com/desmos-labs/desmos/blob/ed22aae536446e39f46aa109663ea02236f00d13/x/posts/internal/types/msgs/msgs.go#L135

If the posts contain media or poll data, it can never be updated. Desmos should also support editing the media and poll data.

**Comment by bragaz** [comment]
@RiccardoM should we implement this in the next version?

**Comment by RiccardoM** [comment]
@bragaz Yes you can take care of this
