### ISSUE TITLE
Revise the singular and plural forms of variables

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#203]
The variables using for media is not correct and may mislead in development.

https://github.com/desmos-labs/desmos/blob/ed22aae536446e39f46aa109663ea02236f00d13/x/posts/internal/types/models/common/post_media.go#L14

`Media` is the plural form of the word `Medium`. Should we change the type to `PostMedium` and the variable of the slice `PostMedia` instead of `PostMedias`, and the object in the msg type `Media` instead of `Medias`?

**Comment by bragaz** [comment]
Yes you are right, I'm okay with this. We could apply this in `0.9.0`

**Comment by RiccardoM** [comment]
Probably, what we could do is rename the entire `Media` thing to be `Attachment` (with plural `Attachments`) instead. This would also make it more clear. 

What do you think @kwunyeung @bragaz?

**Comment by kwunyeung** [comment]
@RiccardoM good idea! 🎉

**Comment by bragaz** [comment]
@RiccardoM I'll take care of this ok?

**Comment by RiccardoM** [comment]
> @RiccardoM I'll take care of this ok?

Sure
