### ISSUE TITLE
Replace CircleCI and Travis with GitHub Actions

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#213]
Currently we are using Circle CI and Travis to build and run our CI/CD system. 

After testing GitHub actions inside Mooncake, I think we should definitely switch to using it also here, since it makes it easier to implement new features over time.

**Comment by bragaz** [comment]
I found this on reddit and I think it could be useful for this: 
https://blog.bitsrc.io/what-are-github-actions-and-how-to-use-them-e89904201a41

**Comment by RiccardoM** [comment]
@bragaz Thanks! also, I've seen that Cosmos has already started using GitHub actions as well: https://github.com/cosmos/cosmos-sdk/tree/master/.github/workflows
