### ISSUE TITLE
Remove user specified post creation time and last edited in favor of block time usage

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#215]
## Context
Currently when the user creates a post, it needs to specify by-hand the `CreationDate` and `LastEdited` values. This approach has some pros and cons to it. 

**PROs**
- It allows developers to specify a past creation date, so that they can post all their posts to Desmos easily
- It allows developers to create a post with a specific date, and then sync them to the chain easily in a second time, making sure the creation time is not changed

**CONs**
- It requires us to validate the creation and last edit times each time a new post is created or an existing one is edited, to make sure that the creation date is not equals or after the last edit one
- It requires us to validate the creation and last edit time to make sure they are not in the future based on the current block time

I was actually thinking about replacing those times with the value of `ctx.BlokTime()`: 

- if the post is being created, `post.CreationDate = ctx.BlockTime()`
- if the post is being edited, `post.LastEdit = ctx.BlockTime()`

This would solve the two above mentioned **cons**, but remote the above mentioned **pros**. 

What do you @kwunyeung @bragaz think about this? What option do you think is the best? Leaving it as it is, or replacing the values with the current block time?

**Comment by bragaz** [comment]
Using `ctx.BlockTime()` is a good idea. 
Removing that checks will make the code easier and in the meantime we will be 100% sure that all the posts' dates are correct. I'm totally in favour of this! 👍

**Comment by kwunyeung** [comment]
Yes those **pros** are the reason I originally built the `posts` module like this. And one more concern was if a user post at a certain time and then the post is being committed at a later block, the time will look strange to the user. However, after using `Mooncake` for a while, I think this concern doesn't really exist when we only show a relative timeago. I was thinking too much at the very beginning.

So yes, please go ahead and use the `ctx.BlockTime()`. 👍
