### ISSUE TITLE
Allows the users to give their tag away

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#225]
## Feature description 
Currently when the user creates a profile, his DTag is selected once initially and then it can never change. However, I think there might be some cases in which two users might agree on a DTag exchange, or one user might want to give away his DTag to another user. 

An example could be a user registering the DTag `microsoft` initially, and then wanting to sell that DTag to the real Microsoft company later.

## Implementation proposal
In order to implement this possibility, I think we can simply create a new message type, named maybe something like `MsgTransferDTag` formed as follows:

```golang
type MsgTransferDTag struct {
  CurrentOwner  sdk.AccAddress `json:"current_owner" yaml:"current_owner"`
  ReceivingUser sdk.AccAddress `json:"receiving_user" yaml:"receiving_user"`
}
```

Thsi message, when handled, would simply take the current DTag of the `CurrentOwner` and transfer it to the `ReceivingUser`. Also, if the `ReceivingUser` already has a DTag, such DTag will be transfered to the `CurrentOwner`, de-facto creating a mechanism by which two users can exchange their tags. 

What do you guys think about this? @kwunyeung @bragaz

**Comment by kwunyeung** [comment]
This is a nice initiative which the `DTag` can become an exchangeable asset. One issue would be if a `DTag` is mentioned in a post content in the future but not only as addresses in media tagging? We need to handle that to reduce confusion and avoid linking to wrong profile.

**Comment by RiccardoM** [comment]
@kwunyeung I've talked about tagging inside #226. I'll move the discussion there

**Comment by bragaz** [comment]
This would be a nice feature for `DSM` usage.
I'm wondering if we need an additional `price` field into the message that would be the dtag's price that users have decided off-chain (in the case that a user is selling his dtag to another).

**Comment by RiccardoM** [comment]
> I'm wondering if we need an additional `price` field into the message that would be the dtag's price that users have decided off-chain (in the case that a user is selling his dtag to another).

I've thought about this as well, but then decided to not include it inside the proposal just to make sure users can also exchange DTags without having to pay. Also, I thought that if a user wants to sell something to another user, he can simply ask the latter to send him some tokens with a simple `MsgSend`. 

One other thing that comes to my mind right now is that we need a double-way confirmation for this kind of operation. If Alice wants to send her DTag to Bob, since Bob would send Alice his own, he needs to confirm this. So, aside from the proposed `MsgTransferDTag` message, we should also have a `MsgAcceptDTagTransfer` to make sure everything goes smoothly and both of the users agree on the exchange.

**Comment by bragaz** [comment]
Probably using `cosmwasm` in future a smart contract could handle the whole process.
Btw using these two steps seems the best solution now.
