### ISSUE TITLE
Standard or minimum transaction fee

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#230]
## Feature description 

Be default, `Cosmos-SDK` let full nodes to define their `min-gas-prices`. This would lead to `Desmos` have a chance of facing zero-fee spam attack. I think we have to setup a minimum or standard fee structure for different `Posts` and `Reports` message types. We should not let users be able to post, make reactions or report without any fee. We can keep the way how other `StdTx` is working but only keeps transactions in `Posts` and `Reports` module have such constraints.

**IRISnet** has a standard minimum fee and **e-Money** has a PoA configurable minimum fee. I think we can learn how they are doing. While we are still studying the tokenomics and usage of a secondary fee token, we can first test this mechanism with the testing `udaric`. There is a module based `AnteDecorator` in the SDK for customizing the `AnteHandler`. Can this be achieved by making use of it?

**Comment by RiccardoM** [comment]
@kwunyeung Yes, this can be easily achieved using the `AnteDecorator` and making sure that a min fee is included if the transaction contains one of the above mentioned message types. 

Do we have any idea on the min fee to be paid for each message?

**Comment by kwunyeung** [comment]
We can keep the current testing amount `0.01 Daric` first.
