### ISSUE TITLE
Profiles module parameters REST endpoint not working

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#244]
## Bug description
The `/profiles/params` endpoint is currently not working: 

## Steps to reproduce
Try visiting http://lcd.morpheus.desmos.network:1317/profiles/params

## Expected behavior
The parameters should be returned properly. 

## Possible solution
I think this bug is caused due to the order in which the endpoints are declared: 

```golang
r.HandleFunc("/profiles/{address_or_dtag}", queryProfileHandlerFn(cliCtx)).Methods("GET")
r.HandleFunc("/profiles", queryProfilesHandlerFn(cliCtx)).Methods("GET")
r.HandleFunc("/profiles/params", queryProfilesParamsHandlerFn(cliCtx)).Methods("GET")
```

Since `/profiles/params` matches the first (with `address_or_dtag = params`), the last one will never get called. By making the last one the first declared, this bug should be fixed:

```golang
r.HandleFunc("/profiles/params", queryProfilesParamsHandlerFn(cliCtx)).Methods("GET")

r.HandleFunc("/profiles/{address_or_dtag}", queryProfileHandlerFn(cliCtx)).Methods("GET")
r.HandleFunc("/profiles", queryProfilesHandlerFn(cliCtx)).Methods("GET")
```

Also, I would advise in renaming the `params` into `parameters`, to match other existing endpoints:

```
/staking/parameters
/slashing/parameters
...
```

**Comment by bragaz** [comment]
I'll take care, I will rename also `posts` params endpoint

**Comment by RiccardoM** [comment]
@bragaz That one is tracked inside #245
