### ISSUE TITLE
Missing types documentation

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#246]
## Context
Currently inside the documentation website (https://docs.desmos.network/) the `profiles` and `reports` types are completely missing. I think we should add them to allow developers to use them properly. 

## Possible fix
Looking at the source code, I think that the only thing missing is the link from the side menu to such pages. Currently that menu sections is defined as follows: 

```js
{
    title: "Types",
    collapsable: true,
    children: [
        ["types/post", "Post"],
        ["types/post-media", "PostMedia"],
        ["types/post-poll-data", "PollData"],
    ]
}
```

By adding the missing links we should be good to go. 

P.S. It's always nice to try out the built docs with `npm run docs:serve` to make sure the links are there.

**Comment by bragaz** [comment]
I totally forgot about adding theme there! My bad, I will add them ASAP and submit a PR.
