### ISSUE TITLE
Automate the default bond denom value setting

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#25]
Currently when starting the chain, after the genesis creation, we need to remember to edit the `genesis.json` file and change the `bond_denom` param inside the `staking` module from `stake` to `desmos`.

I personally find this thing a little bit tedious to do  by hand and I think we can automate it by creating a wrapper `staking` module that acts exactly as the default one but simply sets the proper `bond_denom` value (`desmos`) during genesis.  

This would allow for easier on-boarding of new developers and faster local development of the chain itself.

**Comment by kwunyeung** [comment]
That would be great. Or we can add a flag to the command too. https://github.com/cosmos/cosmos-sdk/issues/5228

**Comment by kwunyeung** [comment]
How about updating the `staking` module directly and make a PR to the SDK? https://github.com/cosmos/cosmos-sdk/issues/5228#issuecomment-544987386

**Comment by RiccardoM** [comment]
Cosmos SDK PR reference: cosmos/cosmos-sdk#5247

**Comment by kwunyeung** [comment]
What do you think about Henrik's approach? I do notice that the params can be overridden but doing this to every module we would like to change looks a bit ad-hoc and Bez comment seems valid. Unless there is a method signature in the module interface, there is currently no elegant way to do this.
