### ISSUE TITLE
Remove the Open field from the PollData

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#252]
Currently the poll object contains a field names `Open` of type boolean that tells whether the poll is still open or not. Since there is already the `Ends` field telling when the post will end, I think that it's best to remove the `Open` field at all. This would make the whole code easier to handle. We would not need a `BeginBlocker` iterating over all the polls and setting that field automatically. Also, clients would rely only on one field to make sure if the poll is closed or not (the ending date). 

Inside the hanlder, we could simply verify that users are not voting to closed polls by using the `ctx.BlockTime` variable and comparing it with the poll ending date.

**Comment by bragaz** [comment]
I can take care of this
