### ISSUE TITLE
Split the magpie module

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#26]
Currently all the features are present inside the `magpie` module. I personally think that we should split those features into different modules. They might be the following ones:

- `magpie` for cross-chain sessions
- `posts` for posts and likes
- `discussions` for discussions proposed into #13 
- `polls` for polls proposed into #14

**Comment by kwunyeung** [comment]
Yes `magpie` and `posts` should be separate modules. I'm thinking if the discussions and polls can be a structure of `Post`. 

Discussion is actually the same as `Post` -> `Reply` -> `Reply` interactions with a specific topic attached. It seems we only need to add a `Title` field in the [`Post` type](https://github.com/desmos-labs/desmos/blob/develop/x/magpie/types/types.go#L14) and it will do the job.  The driver of #13 is from the discussion of `gov` proposal on Cosmos Hub. Imagine if the discussion happens directly on a particular proposal page of Big Dipper or other explorers. We don't have to cross reference to the Cosmos forum everytime and delegators can comments anonymously.

`Poll` is also a `Reply` to the parent `Post` where the parent `Post` is attached with an array of options. The `Reply` must be one of the options defined in the parent `Post`.
