### ISSUE TITLE
Node stop with Failed to write response

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#289]
## Bug description

`morpheus-10000` suddenly stopped due to `Poseidon` was down. From the log, it was down because

```
cosmovisor[5635]: E[2020-10-07|18:59:15.344] Failed to write response                     module=rpc-server protocol=websocket remote=161.81.171.147:61015 msg="RPCResponse
```

Full log is at [here](https://pastebin.com/bYD1rpAc).

I saw similar behaviour from explorer nodes with RPC being requested frequently on Kava and Band before but it should have been fixed. Will look for related issue from Tendermint Core.

**Comment by RiccardoM** [comment]
Filed tendermint/tendermint#5475

**Comment by RiccardoM** [comment]
Closing this as it never happened again
