### ISSUE TITLE
Multiple DTag transfers between the same accounts are not allowed

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#295]
## Bug description
Looking at transaction [E3CA26225BD97E2886FCF5C405A3C5091C43166BDE6AA9ED66C7A2F1775EE075](http://lcd.morpheus.desmos.network:1317/txs/E3CA26225BD97E2886FCF5C405A3C5091C43166BDE6AA9ED66C7A2F1775EE075), we can see that this failed with the following error:

```
the transfer request from desmos1rpurg200edtv6rgvfjuf7j6s8mghnsljkzvurg to desmos1k7q92w7ku72ycutz6xqrx67v92yycff3emz88s has already been made
```

As this says, it looks like that once a DTag transferring from A to B is concluded, no more transfers can be done. 

To be honest, I think this should not be the case. There might be a lot of cases in which A wants to transfer more than one DTag to B. 

For this reason, I think that once a DTag trade has been concluded, no trace of such trace should be kept and the same users should be allowed to trade again.

## Steps to reproduce
1. From Alice, request Bob's DTag. 
2. From Bob, accept Alice's request.
3. From Alice, request Bob's DTag again. 

## Expected behavior
The second request from Alice to Bob should not error and the trading process should start again.

**Comment by bragaz** [comment]
@RiccardoM I've tested this and the situation didn't show up and everything works as intended.
If you take a look at lines 234/235 of the `profiles` `handler` you can see that after the request's acceptance the requests stores of both owner and recipient are flushed.

**Comment by RiccardoM** [comment]
@bragaz I think this was caused by a series of unfortunate events that happened and I've described inside #296. Can we however add a test case to show that the steps above work properly? Maybe something like a simulation somewhere or even a unit test running the handler with different messages one after the other

**Comment by bragaz** [comment]
@RiccardoM I could set up an integration tests that check if whole process works properly

**Comment by RiccardoM** [comment]
@bragaz Yeah, that would be nice to have!
