### ISSUE TITLE
Reject DTag transfers

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#297]
## Feature description 
Currently, during the DTag transferring process, there is no way for a user to reject a DTag request. This, together with the fact that trades are kept "suspended" if the sending user's DTag changes, can cause strange situations. 

Let's consider the situation in which Alice has DTag `first` and Bob wants it. Then this happens:

1. Bob sends a request to Alice for her DTag. 
2. Alice changes her DTag to `second`. 

In this case the following would occur: 

1. The initial Bob's request cannot be accepted anymore since Alice has changed her DTag. 
2. Bob cannot send a new DTag request to Alice since the request is already opened. 
3. Bob cannot delete the initial request to open a new one.

## Implementation proposal
In order to solve this problem, I think we should implement the following processes: 

1. If Alice's DTag changes, all the requests made **towards** her should be deleted. 
2. Once that Alice accepts a DTag request, all requests made **towards** her should be deleted.

Also, we should implement two new message types:

1. `MsgCancelDTagRequest`  
   This can be used only by the user who started the request, and it cancels the process by deleting the request itself. 
2. `MsgRejectDTagRequest`   
   This can be used only by the user who is asked for their DTag. This also cancels the process.

**Comment by bragaz** [comment]
The 2nd point of the implementation proposal is already implemented.
The system deletes all the Alice and Bob requests after the acceptance of a request.
For everything else I'll start right now!
