### ISSUE TITLE
Implement proper blocking usage

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#298]
## Feature description 
Currently, when a user blocks another user that blockage is never considered anywhere. Instead, we should consider it when: 

1. a blocked user asks for the DTag of the blocking user;
2. a blocked user adds a relationship towards the blocking user.

## Implementation proposal
What I think we should do is the following: 

1. when a DTag transferring request is made from Alice to Bob, check if Bob has blocked Alice. If so, return an error and halt the process;

2. when a relationships is created from Alice towards Bob, check if Bob has blocked Alice. If so, return an error and halt the process.

**Comment by bragaz** [comment]
After we close the v0.13.0 I will star with this
