### ISSUE TITLE
Add generate testnet scripts

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#33]
Add script to `Makefile` to generate testnet automatically. The script will do the follow steps.

1. Init genesis file
2. Update bond denom
3. Create 4 `.desmosd` and `.desmoscli` home directories
4. Create 1 key in each `.desmoscli` home directory
5. Add genesis accounts to all 4 addresses
6. Create gentx with the 4 keys from different directories
7. Copy all gentx to one single gentx directory
8. Collect gentxs
9. Copy the generated genesis file to each `.desmosd/config` directory
10. Update ports to the genesis files in each `.desmosd/config` directory
11. Run `make install`
12. Start 4 nodes with 4 different `.desmosd` home directories

**Comment by RiccardoM** [comment]
Why do we need to generate a testnet with 4 nodes and cannot simply use a testnet with one node?

**Comment by kwunyeung** [comment]
1. Test more than one node to make sure consensus can be made.
2. 4 nodes with same voting power to simulate the lowest number of nodes in BFT (3n+1).

**Comment by kwunyeung** [comment]
Adapt the `gaia testnet` command.

https://github.com/cosmos/gaia/blob/master/cmd/gaiad/testnet.go
