### ISSUE TITLE
Block Height Higher Than Core

### ISSUE THREAD

**Issue by lightiv** [desmos-labs/desmos#335]
## Bug description

SkyNet: https://morpheus.desmos.network/validator/desmosvaloper1usxulamszd7myr0fa9g0klk3gv906tqgpd00du

I found my validator had been jail for a number of days, Dec 17, 2020, despite it still reading block.  I attempted to unjail which appeared to work.  later I found that it was no longer reading blocks and attempted to restart it.  Upon restart I received the following error:

Dec 30 23:18:58 desmos-dsm systemd[1]: desmosd.service: Scheduled restart job, restart counter is at 3.
Dec 30 23:18:58 desmos-dsm systemd[1]: Stopped Desmosd Full Node Daemon.
Dec 30 23:18:58 desmos-dsm systemd[1]: Started Desmosd Full Node Daemon.
Dec 30 23:18:58 desmos-dsm desmosd[3123]: I[2020-12-30|23:18:58.651] starting ABCI with Tendermint                module=main
Dec 30 23:18:59 desmos-dsm desmosd[3123]: ERROR: error during handshake: error on replay: app block height (1219525) is higher than core (1219256)

## Steps to reproduce
 

See the description above.  Steps are as described.

## Expected behavior

The validator should have restarted and began syncing again.

**Comment by RiccardoM** [comment]
Closing this as we've never seen this happened again
