### ISSUE TITLE
Should we name the new binary desmos instead of desmosd?

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#342]
As we will have a single binary after upgrading to `Stargate`, some client commands starting with `desmosd` will be not very sensible. For example,

```
desmosd keys add ...
```

The trailing `d` original refers to the server daemon. It may create confusion it we keep the `d` for client commands. I would suggest we rename the binary to `desmos` only.

**Comment by bragaz** [comment]
I was thinking the same
