### ISSUE TITLE
Missing configuration support

### ISSUE THREAD

**Issue by koen84** [desmos-labs/desmos#353]
## Bug description
Commands are failing (or returning wrong info) when desmos is run on custom ports.

## Steps to reproduce
Run desmos on custom port (in particular change 26657) and run e.g. `desmos query bank balances <account-addres>`

## Expected behavior
When running a command, desmos should pick up the connection parameters from its config file, rather than user specifying `--node tcp://localhost:<custom-port>`

**Comment by RiccardoM** [comment]
This option was deleted from Cosmos since version `v0.40.0`. Currently there's a discussion inside cosmos/cosmos-sdk#8529 and an implementation proposal inside cosmos/cosmos-sdk#8820. We can only wait until this is added back into Cosmos, and then upgrade.
