### ISSUE TITLE
gRPC gateway endpoint /cosmos/tx/v1beta1/txs/ is missing

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#370]
## Bug description

The gRPC gateway endpoint for querying tx is missing in `morpheus-13001`. The legacy API works.

## Steps to reproduce
 
When query with 

http://lcd.morpheus.desmos.network:1317/cosmos/tx/v1beta1/txs/6A6EE7B8F79358D1C1ACDA5792A39E439439B39690E23712D38AE29724009D38

returns `Not Implemented`.

However, the legacy API works

http://lcd.morpheus.desmos.network:1317/txs/6A6EE7B8F79358D1C1ACDA5792A39E439439B39690E23712D38AE29724009D38

**Comment by RiccardoM** [comment]
@kwunyeung Is this endpoint present on the Cosmos Hub?

**Comment by kwunyeung** [comment]
@RiccardoM yes it is
