### ISSUE TITLE
Implement manageable subspaces

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#392]
## Feature description 
Following the [_"Extend the concept of subspace"_ discussion](https://github.com/desmos-labs/desmos/discussions/375_), we should implement editable subspaces.

## Implementation proposal
We would like to implement a new module called `x/subspaces` inside which every subspace is represented by an entity that has the following attributes: 

- and `id`, which is a unique SHA-256 hash that can be used to reference such subspace while creating posts;
- an `owner` which is going to be the profile that first registers that subspace; 
- an optional list of `admins` that represent the users allowed to perform special operations inside such subspace.

I think that what we should do is the same that Band Protocol does with data sources. Citing their documentation website: 

> When registering the data source, the message sender can choose whether to specify an owner of the source. If an owner is specified, only the owner can make any changes to the data source once it is registered

This should be the same behavior that we should implement with subspaces. The user that registers a subspace should be allowed to specify a different owner of such subspace. If they do not specify an owner, the subspace will not be editable later. Otherwise, only the owner will be able to edit it. 

### Admins
Since we want the subspace to be manageable, we should allow the owner to add or remove admins to the subspace. 

This should be done using two different messages that can be sent **only by the creator of the subspace**: `MsgAddAdmin` and `MsgRemoveAdmin`. 

Each admin should be able to perform some administering operations. These initially can be limited to: 

- allowing a specific user to use the subspace (`MsgAllowUser`); 
- removing the ability for a specific user to use the subspace (`MsgRemoveUser`).

#### Notes
We should edit the existing `posts` and `reports` modules to make sure that users who are blocked from using a subspace are not able to:

- create, comment or react to posts present inside such subspace, and
- report posts present inside such subspace

**Comment by bragaz** [comment]
Hey @RiccardoM I was thinking, what about a message to transfer the ownership of the subspace? 
I think it would be useful to face cosmos discord like situations
