### ISSUE TITLE
Run JS or Python VM on fullnode

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#4]
We should let other platforms to run "smart contracts" (I always don't like this term tbh) using already wide-adopted languages like JS and Python. There are a few Go specific VM for the both languages. As long as Desmos stick to the limited available features for social network, the overhead of running those scripts should not be too heavy. If really too heavy, we can introduce off-loading some tasks to GPU.

**Comment by RiccardoM** [comment]
Closed in favor of [Juno](https://github.com/desmos-labs/djuno).
