### ISSUE TITLE
Multisig supports for creating session

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#41]
Some validators or delegators on different chain may be using a multisig address to operate, e.g. Sikka and Iqlusion. The current create session function only validate with an account with a single signature. The create session function should support multisig addresses.

**Comment by RiccardoM** [comment]
Do we have a specification link on how multisigs are created and thus can be verified?

**Comment by kwunyeung** [comment]
May start from this.

https://github.com/cosmos/cosmos-sdk/blob/v0.37.4/x/auth/client/cli/tx_multisign.go#L96

It verifies each signature.

**Comment by RiccardoM** [comment]
I think that we can close this in favor of #114 and #192. What do you think? Thanks to IBC we will no longer have to maintain this module and everything should work properly and faster.

**Comment by kwunyeung** [comment]
Agree
