### ISSUE TITLE
Saving a profile the first time stores `[do-not-modify]` info

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#414]
## Bug description
If you use the `desmos tx profiles save Test` command the first time, the stored profile will contain `[do-not-modify]` values. 

Example can be found on tx with has `EEABCCC94F64863EBE523B9AB885E07D699FB7787F4316B048BBAE2C848B7B20` on Apollo.

## Steps to reproduce
Run `desmos tx profiles save <DTag>` from an account that does not have a profile yet. 

## Expected behavior
No `[do-not-modify]` value should exist. Empty strings should be used instead.

**Comment by bragaz** [comment]
I think those values are only showed inside the tx json but they're not store on-chain.
You can check by doing `desmos q profiles profile desmos1v7thhhpzft9jpgd3a7jjpfdcwfmw7t36aam4qh`
