### ISSUE TITLE
Standardize `PostID` naming conventions

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#419]
Currently inside the codebase we use many different ways to refer to post ids. Some of these are `postid`, `id`, `PostID`, `postID`, `postId` etc. 

In order to make the code more easy to read, we should standardize the naming of such variables. For this reason, I propose to use the following two syntax: 

- `PostID` when used as a struct field
- `postID` when used as a variable 

Obviously, the same follows for parent ids: 

- `ParentID` 
- `parentID`

**Comment by bragaz** [comment]
That's right. Let me handle this
