### ISSUE TITLE
Distribution module is not setup correctly for the community pool proposal

### ISSUE THREAD

**Issue by ryuash** [desmos-labs/desmos#421]
## Bug description

I was trying to test all proposal types and came across the following for `community pool proposal`

![image](https://user-images.githubusercontent.com/42913823/118217719-9dce9900-b4a8-11eb-943f-18e0f4c3ff47.png)

## Steps to reproduce
 

Run in cli

```
desmos tx gov submit-proposal community-pool-spend ~/proposals/pool.json --from your-key --chain-id morpheus-apollo-1 --gas auto --gas-adjustment 1.3 --gas-prices 0.0001udaric
```

`pool.json`

```
{
  "title": "Community Pool Spend",
  "description": "Pay me some Atoms!",
  "recipient": "desmos124xa66ghhq5hrgv28slhmszgvcqa0skcfwphh3",
  "amount": "100000000udaric",
  "deposit": "1000udaric"
}
```

## Expected behavior

To work.

**Comment by kwunyeung** [comment]
Missing the community pool spend proposal handler in `x/gov`. https://github.com/cosmos/gaia/blob/830c0ca8d23b6447e276771c1ecf556880dc1d51/app/app.go#L278
