### ISSUE TITLE
Improve `DTag` regex 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#425]
Currently inside the chain (and the default params of the `x/profiles` module) we are using a RegEx that does **not** end with `$`. I think we should add this since it would make for a better control of the value overall.

**Comment by bragaz** [comment]
[This](https://github.com/desmos-labs/desmos/blob/e847d726e91478b6770fc6aa82ce9942ad4401bb/x/profiles/types/params.go#L21) has the `$` at the end and also [this one](https://github.com/desmos-labs/desmos/blob/e847d726e91478b6770fc6aa82ce9942ad4401bb/x/commons/commons.go#L9) . Which one you're referring to? @RiccardoM
