### ISSUE TITLE
Add the documentation for the whole project

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#43]
Currently there is no documentation at all about message types, starting a new chain etc. 
We should definitely create a `docs.desmos.network` website where developers can get an insight on how to build a Desmos-based application.

**Comment by kwunyeung** [comment]
Same here. I was looking for applications to build our documentation site. Many Cosmos projects are using [Vuepress](https://vuepress.vuejs.org/). I think it's originated by the original doc site of Cosmos SDK. I'm think if [Ghost](https://ghost.org/) would be a better choice for us.

**Comment by RiccardoM** [comment]
@kwunyeung I think the usage of Vuepress is so high due to it's easy integration with Github pages. 
By using Vuepress you can setup the CI so that each time a new tag is created, the documentation website is automatically built and published to keep it always up-to-date with the latest changes. 

I was taking a look at Ghost and it does not seem to have such feature, but maybe I'm wrong. 

I have some experience in Vuepress and can easily set it up in a couple of days if you want to take a look at how it would feel. On the other hand, I've never played with Ghost so I would not know where to start from.

**Comment by kwunyeung** [comment]
@RiccardoM then we can go for Vuepress if you are already familiar with it. I was thinking if we may need other teammates to edit the page but maybe this is not necessary as the documentation should all be technical writings.
