### ISSUE TITLE
Split `x/profiles` keeper into multiple files

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#430]
Currently we have a single `x/profiles/keeper/keeper.go` file containing all the methods. I think it would be much better splitting it into multiple ones such as: 

- `keeper.go` 
- `keeper_dtag_transfers.go` 
- `keeper_blocks.go` 
- `keeper_relationships.go` 

All other files (eg. simulations, etc) should be split as well to improve maintainability

**Comment by bragaz** [comment]
Do you want to split also `msgServer` ?

**Comment by RiccardoM** [comment]
@bragaz Yeah I think it would be better since we're going to implement the IBC profiles soon
