### ISSUE TITLE
Add the `spec` folder to the various modules

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#437]
Currently our custom modules do not provide any `spec` folder as other Cosmos modules do (eg. [auth](https://github.com/cosmos/cosmos-sdk/tree/master/x/auth/spec), [bank](https://github.com/cosmos/cosmos-sdk/tree/master/x/bank/spec), [gov](https://github.com/cosmos/cosmos-sdk/tree/master/x/gov/spec), etc). 

We should add a `spec` folder with the proper details in each of our modules.

**Comment by bragaz** [comment]
Close this because all the modules now have specs
