### ISSUE TITLE
Switch `DisableComments` field to enum type

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#445]
Working on `x/subspaces` I remembered that the `DisableComments` field of `x/posts` could give us the same problems when it comes to handle its default value from the CLI if the user doesn't explicit it.
To be more explicit:
Actually we don't give the possibility through the `MsgEditPost` to edit the `DisableComments` field which I think is limiting.   
If we're going to implement it, it will be hard to manage the situation when a user doesn't specify the field because he doesn't want to edit it. So what default value should we use for that? If originally the `disableComments` field is set to `true` and the default it's `false` it will be difficult to handle this after inside the module.
For this reason I suggest to implement the field like [x/gov](https://github.com/cosmos/cosmos-sdk/blob/master/proto/cosmos/gov/v1beta1/gov.proto#L17).
E.g:
```protobuf
// Comments contains all the possible comments values
enum Comments {
  option (gogoproto.goproto_enum_prefix) = false;

  // ALLOWED tells that's possible to comment a post
  ALLOWED = 0 [(gogoproto.enumvalue_customname) = "Allowed"];

  // NOT_ALLOWED tells that's not possible to comment a post
  NOT_ALLOWED = 1 [(gogoproto.enumvalue_customname) = "NotAllowed"];
}
```

**Comment by RiccardoM** [comment]
If this is implemented, we can then rename the field from `DisableComments` to a more comprehensible `CommentsState` that can can have `COMMENTS_STATE_ALLOWED` and `COMMENTS_STATE_BLOCKED` as values
