### ISSUE TITLE
Implement the usage of subkey

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#45]
Posting posts, replies, likes, etc are frequent activities. These actions should be separated from the key for asset storage as the posting key may be leaving on the web browser, mobile app for easy accessing with low security measure. There is a [subkey proposal](https://gist.github.com/aaronc/b60628017352df5983791cad30babe56) on `Cosmos-SDK` which was first implemented during the Berlin HackAtom 2019. This has already been added to the [`v0.38` milestone](https://github.com/cosmos/cosmos-sdk/issues/5172). 

Borrowing the concepts from Steemit.com

**Posting Key permissions**
Use your Posting Key to:

1. Publish a post or comment
2. Edit a post or comment
3. Upvote or downvote
4. Resteem content
5. Follow people
6. Mute accounts

**Active Key permissions**
Use your Active Key to:

1. Transfer tokens
2. Power STEEM up or down
3. SBD conversion
4. Vote for witnesses
5. Place an order on an exchange
6. Certain profile changes
7. Publish a Witness price feed
8. Create a new user

**Owner Key permissions**
Use your Owner Key to:

1. Reset Owner, Active, and Posting keys
2. Recover your account
3. Decline voting rights

**Comment by bragaz** [comment]
This can be achieved with:
https://github.com/CosmWasm/cosmwasm-plus/tree/master/contracts/cw1-subkeys

**Comment by RiccardoM** [comment]
Closing this as it can be implemented with `x/authz` and the above mentioned `cw1-subkeys`
