### ISSUE TITLE
Add subspaces checks to `posts`

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#464]
## Feature description 
With the introduction of the `x/subspaces` module it's necessary to add some checks to `x/posts` actions to make sure they're made respecting the constraints that might be applied to a specific user inside a subspace.   
These check affect all the following `x/posts` operations :

- `CreatePost`
- `EditPost`
- `AddPostReaction`
- `RemovePostReaction`
- `RegisterReaction`
- `AnswerPoll`
- `ReportPost`

## Implementation proposal
The `x/posts` module can perform these checks by calling the `x/subspaces` keeper that can be introduced inside the module as an expected keeper.

Any thoughts? Something to add?

**Comment by RiccardoM** [comment]
@bragaz Perfect implementation proposal: create an expected keeper with a couple of methods and then call them from the `x/posts` module. I propose the following methods that should implement all the operations the `x/posts` module might want to use:

```golang
type SubspacesKeeper interface {
  // CheckSubspace checks whether the given subspace id references a valid subspace or not
  CheckSubspace(ctx sdk.Context, subspaceID string) error

  // CheckUserPermission checks the permission of the given user inside the subspace with the 
  // given id to make sure they are able to perform operations inside it
  CheckUserPermission(ctx sdk.Context, subspaceID string, user string) error
}
```

**Comment by bragaz** [comment]
@RiccardoM Perfect, I will take care of it.
