### ISSUE TITLE
Add IBC features to `x/subspaces`

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#465]
Today I was thinking about the possible implementation of the IBC for our latest `x/subspaces` module.
In order to put everyone on the same page the new module let the users perform the following actions:

1. Create a subspace
2. Edit a subspace
3. Add/Remove an admin to/from a subspace
4. Register/Unregister a user into/from a subspace
5. Ban/Unban users from a subspace

While talking with @RiccardoM he stated that we might implement only **4** and **5** and let the users administrate a subspace directly from Desmos.
But this is not the only thing we need to care about, checks like those described here https://github.com/desmos-labs/desmos/issues/464 should also be handled accordingly while working with IBC subspaces.

**Comment by RiccardoM** [comment]
Closing this as it will be implemented with InterChain Accounts
