### ISSUE TITLE
Enable snapshot in app.toml by default

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#469]
## Feature description 

From my experience in many different chains developed with `Stargate`, most of the validators or fullnodes would not have snapshot enabled. This make state sync a new node very difficult. I suggest we make snapshot being enabled in `app.toml` by default when the file is being created.

**Comment by dadamu** [comment]
I researched how to implement it. 
The config is generated with the default `state-sync` setting in the [`start`](https://github.com/cosmos/cosmos-sdk/blob/7bca49e2d29460dae7c55fa77aee69ab0810d1f0/x/genutil/client/cli/init.go#L142) cmd.
We can build a custom `start` cmd and simply add a line to enable the state-sync, say:
```go
...
  config.StateSyncConfig.Enable = true
  cfg.WriteConfigFile(filepath.Join(config.RootDir, "config", "config.toml"), config)
  return displayInfo(toPrint)
}
```

Thoughts on it? @RiccardoM @bragaz

**Comment by bragaz** [comment]
@dadamu Great!

**Comment by RiccardoM** [comment]
@kwunyeung @dadamu To be honest, I would not set anything like this as enabled by default. Enabling state sync requires different things to be done: 

1. Set the correct pruning options. 
2. Set the state sync to match those pruning options. 

Aside from this, node operators should also know when this is enabled as it will require more disk space than usual. 

If we want to encourage people in enabling this options, we should do this inside our documentation telling the advantages it will have over the community. I think this will be much more beneficial to everyone instead of silently enabling it for them. They could learn and decide whether or not to enable it.

**Comment by bragaz** [comment]
@RiccardoM mmmmh, I didn't see it from this perspective, you're right, what if we improve the docs in that way then?

**Comment by RiccardoM** [comment]
> @RiccardoM mmmmh, I didn't see it from this perspective, you're right, then we can work on docs improvements for this I guess

Yes, I think this is the best approach. We should tell them why they should enable it (support community, faster sync if they need to migrate, etc) and then tell them how they can do it explaining the meanings of the different settings that can be tweaked

**Comment by kwunyeung** [comment]
Hm... But by default the `pruning` is already set to `default` which means `sanpshot_interval` can be multiples of `500`. If we set the default value to `500`, `1000` or `1500` already make the configurations correct?

I agree we should enhance the doc for storing snapshot. However, if this is a good practice, why don't we set the good practice as default? And then we can mention "We have turn snapshot on by default. If you would like to turn it off, set it to `0`." What do you think?

**Comment by dadamu** [comment]
I think enhancing the doc and setting enable state-sync by default are different things. Enabling it might reduce validators to be confused about why `state-sync` doesn't work. I think there are no cons to desmos networks. 
By the way, setting `snapshot_interval` can be implemented in the same way to build a custom cmd.

**Comment by ryuash** [comment]
Just thought i join this discussion as a recently new validator. I would actually prefer to have snapshots turned on by default with instructions in the docs explaining what snapshot does and how to turn it off.

I think the main reason for this would be laziness and being new, I don't want to edit the config file with too much customization.
 
If it's already turned on by default with a good explanation in the docs and can benefit the chain, I would be less likely to follow the optional instructions on how to turn it off (ex: osmosis). 

On the other hand, I remember being asked to turn on snapshots for apollo on discord and I was simply too lazy. It's optional and just too much work. Now that i'm a little bit more experienced, I can definitely see the affects it has on nodes when there are not enough snapshots available - Many of us are forced to resync the node from genesis.
