### ISSUE TITLE
Implement the pagination to PollAnswers

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#478]
## Feature description 

This issue is for the `PollAnswer` part's implementation of #448.
In the current version, all the poll answers of the poll are stored in one key. Then, it is always used for checking if user answered the poll by `GetPollAnswersByUser`.
It should be split to a answer to be associated to only one key related to  `postID` and `user` so that it can be checked more efficient and paginated when querying. 

## Implementation proposal

The key of the `PollAnswer` can be `postId+userAddress+answerID`. In this way, we can implement the pagination to `PollAnswer`. Besides, we can also refractor the `GetPollAnswersByUser` function to be more efficient.

**Comment by dadamu** [comment]
I double think about the implementation pagination to `PollAnswer` when writing code.

Currently Desmos has three objects to handle the answer: `UserAnswer`, `UserAnswers` and `UserAnswerEntry`.
`UserAnswer` is for creating an answer to a poll, It includes a user address and answers array.
`UserAnswers` is for creating the `UserAnswerEntry` from `UserAnswer`.
`UserAnswerEntry` is for genesis exporting and importing.

To implement pagination to answer. The answer objects can be changed to the following structures:
```proto
// UserAnswer contains the data of a user's answer to a poll for storage
message UserAnswer {
  option (gogoproto.equal) = true;
  option (gogoproto.goproto_stringer) = true;
  
  string post = 1;
  string user = 2;
  string answer = 3;
}

// UserAnswers wraps a list of answers by a user for sending the message
message UserAnswers {
   string user = 1;
   repeated string answers = 2;
}
```
And the key of a user answer could be `postId+userAddress+answerID`.

This allows:
1. Operate a user's poll answers toward the post easily by iterating over `PollAnswersPrefix + '<post-id>' + '<user-address>'`
2. Query all the answers towards the post by iterating over `PollAnswersPrefix + '<post-id>'`
3. Export and import genesis without `UserAnswerEntry`

What do you think? @RiccardoM @bragaz

**Comment by bragaz** [comment]
This looks good! 👍 It will help also reduce the complexity around the polls IMO.
Good job @dadamu!

**Comment by RiccardoM** [comment]
@dadamu I'm having a hard time remembering one thing. Why can't we simply use a single entity named `UserAnswer`? 

```protobuf
// UserAnswer contains the data of a user's answer to a poll
message UserAnswer {
  option (gogoproto.equal) = true;
  option (gogoproto.goproto_stringer) = true;
  
  string post = 1;
  string user = 2;
  repeated string answers = 3;
}
```

This way we can simply use `MsgAnswerPoll`: 

```protobuf
message MsgAnswerPoll {
    string post = 1;
  string user = 2;
  repeated string answers = 3;
}
```

And then we can store the answers as `PollAnswerPrefix + PostID + UserAddress -> UserAnswer.

When we need to export them, we simply export a `[]UserAnswer` and then import them easily. This should be sufficient, or are there any particular cases which make this not sufficient?

**Comment by dadamu** [comment]
@RiccardoM I also thinking about this. By this way, the answer querying would be paginated by user. Then, paginating by user is okay for the case. So, I agree with it.
