### ISSUE TITLE
Change how chain links are stored 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#480]
## Overview
When working towards #472, I realized that currently chain links are stored associated with a profile inside the `Profile` object itself. While this is very handy when querying them, the major downside is that when storing a chain link we need to update the **whole** profile. Since the gas usage is based on how much data is written during a transaction, this will cause later changes to the chain links slice to be extremely costly. Suppose we have a profile with already 10 links, if we add the 11th we need to write the whole slice again so we are writing 10 objects that we should not. 

## Changes proposal
For the above reason, I think what we can do is change how chain links are stored by using the same method we use with other repeated data (eg: DTag requests, blocks, etc): 

```
ChainLinkPrefix + username + chain_name + chain_address -> ChainLink
```

This would allow us to check the existence of a link in O(1) time as well as to query for such link in the same time. 

If this is implemented, the `ProfileByChainLinkQuery` needs to be replaced with a `UserChainLinks` **paginated** query.

Please @dadamu @bragaz let me know what you think about this change.

**Comment by dadamu** [comment]
I highly agree with it. In my opinion, chain links should be isolated from profiles. It brings more flexibility to operate with chain link. And we can avoid the updating all chain links for profile when creating a new link as you said.

**Comment by bragaz** [comment]
As we did for `subspaces` with `admins` and `registered users` this is the best way to go for this too. 💪

**Comment by RiccardoM** [comment]
@dadamu Are you currently working on this? If not, I might be able to pick it up in the next days before starting to review all the tests

**Comment by dadamu** [comment]
@RiccardoM Yes, I am working on it.
