### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#481]
## Context
Currently, our codebase is getting quite large. We now have a lot of features and consequently a lot of tests. I think it's time for us to improve those tests and make them all coherent with one another. In order to do this, I think we need to: 

### 1. Use naming conventions
1. Use `Test<MethodName>` all the tests method. 
2. Use `usecases` for all the use case tests definition:  
   ```golang
   testCases := []struct {
		name           string
		storedProfiles []*types.Profile
		req            *types.QueryProfileRequest
		shouldErr      bool
		expResponse    *types.QueryProfileResponse
	}
   ```
3. Consequently, use `tc` instead of `test` inside for cycles: 
   ```golang
   for _, tc := range usecases {
		tc := tc
   ```
4. Use **lower case names** for all usecases. Instead of 
   ```golang
   name:   "User without profile returns error"
   ```
   Use
   ```golang
   name:   "user without profile returns error"
   ```

### 2. Unspecific error checking
We should not check a specificity of an error, as this might mean changing a lot of tests in the future. Instead of checking for error equality, we should check only if an error is raised. This means using `shouldErr` instead of `expErr` and making this a boolean value: 

```golang
testCases := []struct {
	expPass      bool
}

if tc.expPass {
	suite.Require().NoError(err)
} else {
	suite.Require().Error(err)
}
```

### 3. Ditch all `testData` instances
Currently all the keeper tests use a variable defined inside each suite named `testData` that contains some useful data shared across all tests. While this is surely handy, it might break things in the future. For this reason, I think we should delete all those instances and let each test initialize its state independently if needed. 

### 4. Remove all `stored...` variables in favor of a `store` function
Currently a lot of tests define for each use case the list of things that should be present inside the store before running the tests. They do this by declaring a lot of different slices each one containing the data to be stored when the test runs. While this is handy, it makes it really hard to initialize complex states properly. For this reason, I think we should ditch this method and instead use a `store func(sdk.Context)` method for each usecase: 

```golang
testCases := []struct {
  name   string
  store  func(ctx sdk.Context)
} {
  {
    name: "correct requests returns no error",
    store: func(ctx sdk.Context) {
      profile := suite.CreateProfileFromAddress("cosmos10nsdxxdvy9qka3zv0lzw8z9cnu6kanld8jh773")
      suite.ak.SetAccount(ctx, profile)
    }
  }
}
```

This method will then be called inside each run of different usecases:
```golang
if tc.store != nil {
  tc.store(ctx)
}
```

### 5. Remove redundant `suite.SetupTest` calls in favor of `ctx.CacheContext()`
Currently all keeper usecases initialize the suite everytime they are run to make sure they do not interfere with previous or later runs. This makes them run slower as they need to re-create everything for scratch each time they are run. I propose we change the approach by using the `ctx.CacheContext()` method instead: 

```golang
for _, tc := range testCases {
  tc := tc
  suite.Run(tc.name, func() {
    ctx, _ := suite.ctx.CacheContext()
    if tc.store != nil {
      tc.store(ctx)
    }
  }
}
```

This allows to create a new branched instance of the context that will allow us to perform different operations for each test, but never update the current context. This should result in a faster initialization of the tests as well as faster runs. 

--- 

Please @bragaz @dadamu let met know if you found anything else that we can improve.

**Comment by bragaz** [comment]
@RiccardoM Of course these are useful improvements! I agree with this, can I take care of it since you are working on the centralisation stuff and I'm free?

**Comment by RiccardoM** [comment]
> @RiccardoM Of course these are useful improvements! I agree with this, can I take care of it since you are working on the centralisation stuff and I'm free?

I prefer taking care of this personally once we merge the various opened PR as I want to also add some contribution guidelines to highlight this.

**Comment by dadamu** [comment]
I agree with it. There are many different format that let me confused when writing unit-test.

**Comment by RiccardoM** [comment]
Closing this as it's been implemented with the above PRs for current modules, and it will be the standard for new modules
