### ISSUE TITLE
Improve events emissions

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#482]
## Context
Currently in most modules, events are emitted inside the `msg_server` methods. While this is by default the best way to emit events, it actually does not us allow to emit them when a module uses another module's methods. For this reason, I think we should move all the events possible from the `msg_server` to the keeper methods. When doing so, we should always think if such events are worth emitting every time we call that method or not.

**Comment by bragaz** [comment]
@RiccardoM Considering what you've wrote, shouldn't we move events **only** in those methods who are shared between modules?
Otherwise isn't this worthless?

**Comment by RiccardoM** [comment]
@bragaz Yes I agree

**Comment by bragaz** [comment]
I've checked around the code and we only use `subspaces` module to make some checks inside other modules which I think it's not the case to add events for IMO

**Comment by RiccardoM** [comment]
Closing as no longer necessary
