### ISSUE TITLE
Improve modules logging 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#483]
## Context
Currently the SDK modules are logging useful information using the `Logger` interface. This allows the node to print different levels of information when running (eg. `debug`, `info`, etc). 

To make it easier for node operators to understand how their node is doing, we should implement logging into our modules as well when needed. This can be done by defining a new method for each keeper as follows: 

```golang
func Logger() log.Logger {
  return ctx.Logger().With("module", fmt.Sprintf("x/%s", types.ModuleName))
}
```

Then, we can simply call the various methods (`Info`, `Debug`, ...):

```golang
logger.Info("asserted all invariants", "duration", diff, "height", ctx.BlockHeight())
```

**Comment by bragaz** [comment]
@RiccardoM Should we also add logs to existent methods?

**Comment by RiccardoM** [comment]
@bragaz Yes, logs should be added with different levels (`Info`, `Warn`, `Debug` etc) when we think it would be nice to have them
