### ISSUE TITLE
Add subspace checks to `x/profiles`

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#487]
## Feature description 
Inside the `x/profiles` modules there are some operations that involves subspaces like those related to `relationships` and `blocks`. I think it's worth to add some checks to ensure that both users involved in these kind of operations are registered inside the `subspace` where they're trying to perform these actions. 

We could also add checks inside the `EndBlocker` to see if any of the users involved in relationships is still registered to the subspaces and if not, automatically remove the relationships/blocks. I'm not 100% of this last one, what do you guys think? @RiccardoM @dadamu.

## Implementation proposal
This can be achieved by adding an expected keeper inside the module.
```go
type SubspacesKeeper interface {
  // IsUserRegistered checks the user is registered inside the subspace with the given id
  IsUserRegistered(ctx sdk.Context, subspaceID string, user string) bool
}
```

**Comment by RiccardoM** [comment]
I agree on the checks, but please open a new issue for automatic removal of users as it's a delicate topic and should be discussed separately from this
