### ISSUE TITLE
Like a specific link

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#49]
Sometimes I would like to `Like` an activity like this on Big Dipper subconsciously.

![image](https://user-images.githubusercontent.com/932636/69475323-9cb63180-0e06-11ea-8397-0aa490e64d11.png)

Desmos should have an ability to `Like` such activities as a link and incentivize those being Liked. In this case, if I liked the activity of B-Harvest, B-Harvest will be incentivized and the record will be linked to their Desmos address.

**Comment by RiccardoM** [comment]
I would personally avoid implementing the ability to liking links, as this might become confusing for users and also clients that do not know how to display this. 

Instead, I would suggest clients to create a special king of `Post` containing the wanted link inside the message and setting a particular `topic` (specified inside #46) for them.

**Comment by RiccardoM** [comment]
This can be now done using the `optional_data` that can be specified inside a post.
