### ISSUE TITLE
Implement the pagination to `Report`

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#493]
## Feature description 

This issue is for the `Report` part's implementation of #448.

In the current version, all the reports of the post are store in one key, `ReportPrefix + '<post-id>'`. In addition, A user can report a post repeatedly unless the report content are absolutely same as existing report. 
It could be split to a report to be associated to only one key associated to user so that it can prevent multiple times reports from a user and also can be paginated when querying.

## Implementation proposal

The key can be changed to `ReportPrefix + <post-id> + <reporter-address>`.
This allows:
1. Prevent a user report a post repeatedly
2. Query all the reports for the specific post by iterating over `ReportsPrefix + '<post-id>'`

What do you think? @RiccardoM @bragaz

**Comment by bragaz** [comment]
I agree with you @dadamu. I'm also thinking about some improvements for the `Reports` object, I will open another issue soon

**Comment by RiccardoM** [comment]
@dadamu I agree we should allow only one report per (post - user) tuple. However, as @bragaz said, we should also review the `Report` object implementation. I'm thinking for example to allow multiple reasons to be selected for the report (eg. nudity + other things). I will come more on the issue @bragaz is going to open thought.

**Comment by RiccardoM** [comment]
Closing this as it will be implemented when we re-implement the `x/reports` module
