### ISSUE TITLE
Implementing pagination to UserBlock 

### ISSUE THREAD

**Issue by HarleyAppleChoi** [desmos-labs/desmos#495]
## Feature description 

This is the implenmentation proposal of UserBlock feature at #448
Now for each user there is an array of userblock that is saved in KVStore
`"UsersBlocksStoreKey" -> []UserBlock`
It should be split to a relationship associated to only one key so that query.FilteredPaginate can be used when querying.

## Implementation proposal

KVStore relationship should change from `one to all` to `one to one`/`one to few` , that is 
`"UsersBlocksStoreKey-1" -> UserBlock-1`
`"UsersBlocksStoreKey-2 -> UserBlock-2`

Show what UserBlockStoreKey would be
`UsersBlocksStorePrefix + Blocker +  Subspace ` -> [] blocked Users
So that user can query not only base on the blocker, but also subspace the user block.
However I am not sure if it is enough or we should add more store key to make that one on one. I have trouble comming up more possible key.

**Comment by dadamu** [comment]
@HarleyAppleChoi In my opinion, It should be `one to one` relationship for paginating `UserBlock`. In the way you proposed is paginated by subspace, but not by  blocked user.

What I think it is better to use `UsersBlocksStorePrefix  + Blocker + Subspace + BlockedUser`.
This allows:
1. Query all user block objects by iterating over `UsersBlocksStorePrefix`
2. Query all user block objects created by a blocker by iterating over `UsersBlocksStorePrefix + Blocker`
3. Query all user block objects created by a blocker inside a specific subspace by iterating over `UsersBlocksStorePrefix + Blocker + Subspace`
4. Check if a user block exists or not easily and fast with O(1) time complexity.

**Comment by HarleyAppleChoi** [comment]
@dadamu 
> Check if a user block exists easily and fast with O(1) time complexity.

It is O(1) only if blocker ,subspace and blockedUser are all provided. If subspace isn't provided, it would have O(n) time. Not bad...

**Comment by dadamu** [comment]
@HarleyAppleChoi Yes, you are right. It assumes that blocker, subspace and blockedUser are all provided. I think there is only a case to check the user block exists or not when storing a new user block. Are there any other cases I lost?

**Comment by bragaz** [comment]
I think you pointed all of them out @dadamu

**Comment by bragaz** [comment]
@HarleyAppleChoi would you like to tackle this and implement it?
Usually what we do to introduce a new feature/improvement is
1) Checkout on master branch
2) Create a new branch with the following name convention:
     **your-name/the-feature-name**  e.g **apple/user-block-pagination-impl**
3) Start your implementation
4) Open a PR when you've finished
5) After all the checks passed, you can request a review to any of us: me, Paul, Ricky

Feel free to ask anything to us, and take your time to explore, study and try out the code!
