### ISSUE TITLE
Change how post are responded

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#498]
## Feature description 

In current version, the post response returns whole content includes all the `PostReactions` and `UserAnswers`. In my opinion, both of them in `PostResponse` could be replaced with the total count. As a result, the post response will be much smaller and much more fast when querying. Then, `PostReactions` can also be paginated when querying whole reactions of the post.

## Implementation proposal

Change the post response struct, say:
```proto
message QueryPostResponse {
  desmos.posts.v1beta1.Post post = 1;

  // Answers field show the total count of each answers from user
  map<string, int> answers = 2;

  // Reactions field shows the total count of each reactions from user 
  map<string, int> reactions = 3;

  repeated string children = 4;
}
```
Thoughts on it? @RiccardoM @bragaz

**Comment by RiccardoM** [comment]
I think we can simply delete all the different things that are not the `Post` itself. Developers will be able to use the other gRPC queries to get the data anyway. So the final response can simply be 

```proto
message QueryPostResponse {
  desmos.posts.v1beta1.Post post = 1;
}
```

### Notes
If not already present, we should add the following queries: `GetPostReactions` (paginated) and `GetPostChildren` (paginated)
