### ISSUE TITLE
Change the request of `Posts`

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#500]
## Feature description 

The current grpc query method of `Posts` doesn't have `sortby` function. It could be implemented by the following proposal. 

## Implementation proposal

There are two `sortby` keys for posts query, `postID` and `created`. Besides, it provides two `sort_order` methods, `ascending` and `descending`.  To implement this feature, there are 4 cases should be handled.

### 1. sort by postID ascending

Default `query.FilteredPaginate` can handle this case.

### 2. sort by postID descending

In this case, we should create a function to reverse the paginated order. I think [`ReverseIterator`](https://github.com/cosmos/cosmos-sdk/blob/master/store/prefix/store.go#L108) can implement the pagination function for ordering descending.

### 3. sort by creation time by ascending

In this case, the current store structure can not approach this. I propose creating a new key named `PostCreationKey` having the `Creation time -> Post ID` association so that `Post` can be iterated by creation time easily.

### 4. sort by creation time by descending

Similar with case 2, it could solved it by  `ReverseIterator` with case 3 prefix store.

What do you think? @RiccardoM @bragaz

**Comment by bragaz** [comment]
There's already the predisposition for this in the CLI so yes I'm in favour of it. 
The proposed implementation looks good for me 👍.

**Comment by RiccardoM** [comment]
To be honest, I think we could (and should) remove the ability of sorting all together. Things like these should be handled by some external applications like [DJUno](https://github.com/desmos-labs/desmos) and not from the chain itself. We should only provide the ability to query for paginated posts (like we already do) without the optional sorting things.

**Comment by dadamu** [comment]
@RiccardoM I see, RDBMS has more advantages for an application with complex query and sorting. The Desmos should be focus on data decentralized and security. How about the ability of filtering things like query for posts filtered by parent id, creator and etc.? Should these also be removed?

**Comment by RiccardoM** [comment]
> How about the ability of filtering things like query for posts filtered by parent id, creator and etc.? Should these also be removed?

I think yes. We should create custom gRPC query endpoints to get specific data. For example, `GetPostChildren` or other ones if needed. But we should remove the filtering from the more generic `GetPosts` query, leaving only the required `Subspace` param that should always be present (not empty). We should allow only to get the posts of a specific subspace instead of all the posts ever created. This should also ensure we do not allow users to use the gRPC queries as a DDoS attack vector.

**Comment by dadamu** [comment]
In conclusion, desmos posts should provide query with the optional subspace and creator. All sortby and filter factors should be moved to the application layer (RDBMS) to ensure the desmos networks security. So, I think the store key and cli for `Posts` should have some changes.

## Implementation proposal

### 1. Remove all sortby and filter factor in PostsRequest

### 2. Add new key for querying with the subspace and creator

In current version, posts are stored in db with the key generated by hash function with whole content. To query a specific post created by a creator inside a subspace should use filter function. 
The solution is adding a new key having a format `PostQueryPrefix + '<subspace-id>' + '<creator-address>' | PostID`.

This allows three things, to get all posts, to get posts inside a specific subspace and to get posts created by a user inside a specific subspace.

### 3. Revise CLI query command to `desmos query posts posts [[subspace]] [[address]]`


If I missed anything or anything is incorrect, please correct me. @RiccardoM, @bragaz

**Comment by RiccardoM** [comment]
@dadamu With the proposed key 

`PostQueryPrefix + '<subspace-id>' + '<creator-address>' | PostID`

there will be a problem: if the same user creates two posts within the same subspace, the second one will overwrite the first one. 

Also, I think the `desmos query posts posts [[subspace]] [[address]]` command might not be worth the effort. For this reason, I think we can safely delete the ability to query the posts of a user, and only leave the ability to query the all the (paginated) posts for a given subspace. The key can then simply be 

`PostPrefix + '<subspace-id>' +  | PostID | PostID`

This way by including the PostID inside the key we avoid multiple posts overlapping each other.

**Comment by dadamu** [comment]
@RiccardoM Indeed, I didn't notice that thing, thanks for pointing it out.
I will implement it by #499.
