### ISSUE TITLE
Add `GetPostComments` paginated query method

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#505]
## Feature description 

This issue is related to #498. It does not provide the `GePostChildren` query in the current version. The post children are stored as whole array in a key, and it should be split to `on-to-one` association with the key. 

## Implementation proposal

To implement the pagination to `PostChildren`, the store key should be reconstructed to `PostChildrenStorePrefix + '<parent-id>' + '<child-id>' | Child ID`.

This allows:
1. Get all the children posts of the post
2. Check if a child post exists by O(1) time complexity

Besides, the cli tool provides desmos query posts post-children [post-id] to get all the children posts of the post having the given id.

Thoughts on it? @RiccardoM @bragaz

**Comment by bragaz** [comment]
@dadamu Looks good to me!

**Comment by RiccardoM** [comment]
Looks good to me too

**Comment by dadamu** [comment]
I think renaming the method into `PostComments` would be better.

**Comment by RiccardoM** [comment]
> I think renaming the method into `PostComments` would be better.

Agree :+1:
