### ISSUE TITLE
Improve `Report` type

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#507]
## Feature description 
Some days ago I was looking how CSN handle reports and I've noticed that they all let users select a category (or more then one) from a list of existent categories. I think it should be good to standardise this thing on Desmos.
Currently we only have a generic `type` field (which name is IMO a little bit confusing) that can be any string.
In the long, when there will be a variety of apps using Desmos this will result in a lot of confusions with possibly tons of different categories. 

## Implementation proposal
To improve it, I'm actually thinking about something like this:
```proto
enum Reason {
  option (gogoproto.goproto_enum_prefix) = false;

  NUDITY = 0;
  VIOLENCE = 1;
  INTIMIDATION = 2;
  HARASSMENT = 3;
  SUICIDE = 4;
  SELF_HARM = 5;
  FAKE_INFORMATION = 6;
  SPAM = 7;
  UNAUTHORIZED_SALES = 8;
  TERRORISM = 9;
  OTHERS = 10;
}

// Report is the struct of a post's reports
message Report {
  option (gogoproto.equal) = true;
  option (gogoproto.goproto_stringer) = true;

  // ID of the post for which the report has been created
  string post_id = 1 [
    (gogoproto.customname) = "PostID",
    (gogoproto.jsontag) = "post_id",
    (gogoproto.moretags) = "yaml:\"post_id\""
  ];

  // Identifies the type of the reports
  repeated Reason reasons = 2
      [ (gogoproto.jsontag) = "reasons", (gogoproto.moretags) = "yaml:\"reasons\"" ];

  // User message
  string message = 3 [
    (gogoproto.jsontag) = "message",
    (gogoproto.moretags) = "yaml:\"message\""
  ];

  // Identifies the reporting user
  string user = 4
      [ (gogoproto.jsontag) = "user", (gogoproto.moretags) = "yaml:\"user\"" ];
}
```

I'm just giving an example here and maybe there are better ways to handle this, just pointing this out.
Thoughts? @RiccardoM @dadamu

**Comment by dadamu** [comment]
@bragaz I agree this change. Categorizing reasons in this way would be useful.

By the way, I have a question about what will happen next after reporting. There is not any action, especially deleting the post after reporting in the current version. I am worried about that there will be a lot of posts violating the rights of others.

**Comment by RiccardoM** [comment]
To be honest, I'm not in favor of including all possible reports types as hard-coded. Instead, I think it would be much better to put those possible types as chain parameters so that the governance will be able to add more if needed without us having to release a new version of Desmos all together. For this reason, I would delete the enum and simply add a method that's like 

```golang
func (k Keeper) IsValidReportType(ctx sdk.Context, reportType string) bool {
  types.Contains(k.GetParams(ctx).ReportTypes, reportType)
}
```

**Comment by bragaz** [comment]
@RiccardoM So add them as params with a proposal to add more through gov right?

**Comment by RiccardoM** [comment]
> @RiccardoM So add them as params with a proposal to add more through gov right?

Yeah exactly

**Comment by bragaz** [comment]
Great then. I will take care of this

**Comment by RiccardoM** [comment]
Closing this as it will be discussed when we create a `x/reports` module ADR
