### ISSUE TITLE
Bump SDK to v0.42.6 which solve state sync bugs

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#524]
The Cosmos SDK team has released [v0.42.6](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.6) which includes the Tendermint bug fix on state sync. Suggest to include in the next upgrade.

**Comment by bragaz** [comment]
@RiccardoM I think we can include this in `v0.17.0`

**Comment by RiccardoM** [comment]
This has already been done with https://github.com/desmos-labs/desmos/issues/509
