### ISSUE TITLE
Make profiles query user parameter optional

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#534]
## Context 
Currently when querying the `x/profiles` module data, almost all queries require to specify a single user to which to query the data for. Examples: 

- `query blocks [user]` 
- `query relationships [user]`
- `query incoming-dtag-transfer-requests [user]` 
- ...

While this is surely handy, I think we should allow developers to also query for all such data without specifying a single user. 

## Proposal
My proposal is to make the `[user]` parameter optional on all queries, allowing to get all the stored data with pagination: 

- `query blocks [[user]]` 
- `query relationships [[user]]` 
- `query dtag-transfer-requests` 
   **Note**. This command should be a different one from the `incoming-dtag-transfer-requests` to avoid any confusion 
- ...

Please let me know what you guys think @bragaz @dadamu

**Comment by bragaz** [comment]
This sounds good to me 👍 , plus it can be done easily now with all the paginated requests

**Comment by dadamu** [comment]
It sounds good to me, too. 👍
However, to query all the stored data with `offset` in pagination config would search through all the records ([doc](https://github.com/cosmos/cosmos-sdk/blob/321aed823c882ac893c739c8a4d50905ec702c62/types/query/filtered_pagination.go#L12)). That may be a problem if there are the huge number of the data in store.
Should we also limit the `Offset` and `Limit` in `PageRequest`?

**Comment by bragaz** [comment]
@dadamu maybe it's a good idea

**Comment by RiccardoM** [comment]
> Should we also limit the `Offset` and `Limit` in `PageRequest`?

I think we can avoid doing this. Developers will use the `NextKey` field anyway instead of `Offset` and `Limit`. I think we should keep them as they are without any worry. The worst thing it can happen is they're going to have a very slow response and possibly block their node. We won't have any public RPC anyway.

**Comment by kwunyeung** [comment]
From my experience, most issue due to large return result is from gRPC gateway. At least CLI can handle it but just like what @RiccardoM mentioned the user just has to wait.
