### ISSUE TITLE
Replace `FilteredPaginate` with `Paginate`

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#535]
## Feature description 

Currently, Desmos use `FilteredPaginate` to implement the pagination features, the function should be replaced with `Paginate` without filtering.

## Implementation proposal

Replace all `FilteredPaginate` functions with `Paginate` in `grpc_query.go`.

**Comment by bragaz** [comment]
I've take a quick look to the `Paginate` function and since we don't use any filter for the queries we can switch to it.
Maybe it would we worth to check which of our queries can accept some filters in future and not change them.

**Comment by dadamu** [comment]
@bragaz In my opinion, complex queries with any filter will be handled by `Hasura`, so we can safely replace them.
