### ISSUE TITLE
Improve `x/profiles` params structure

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#538]
## Context
Currently the `x/profiles` parameters are represented by the following structures: 

```golang
type Params struct {
  NicknameParams NicknameParams
  DTagParams     DTagParams
  MaxBioLength   sdk.Int
}

type NicknameParams struct {
  MinNicknameLength sdk.Int
  MaxNicknameLength sdk.Int
}

type DTagParams struct {
  RegEx         string
  MinDTagLength sdk.Int
  MaxDTagLength sdk.Int
}
```

In my opinion there are a bunch of things that can be improved about these structures: 
1. There are many redundant suffixes (`Params`, `Nickname`, etc) 
2. The bio params are not inside a subset of their own

## Implementation proposal
To improve the structure of the parameters I think we can re-defined them as follows: 

```golang
type Params struct {
  Nickanme Nickname
  DTag     DTag
  Bio   Bio
}

type Nickname struct {
  MinLength sdk.Int
  MaxLength sdk.Int
}

type DTag struct {
  ValidityRegEx         string
  MinLength sdk.Int
  MaxLength sdk.Int
}

type Bio struct {
  MaxLenght sdk.Int
}
```

**Comment by bragaz** [comment]
Even though I think these changes are necessaries, while implementing this I felt that these names are too generic and may be confused with a `Nickname` object or a `DTag` object rather than params. I have think about changing them like this:
```go
type Params struct {
  NicknameLimits NicknameLimits
  DTagPolicies DTagPolicies
  BioLimits BioLimits
}

type NicknameLimits struct {
  MinLength sdk.Int
  MaxLength sdk.Int
}

type DTagPolicies struct {
  ValidityRegEx string
  MinLength sdk.Int
  MaxLength sdk.Int
}

type BioLimits struct {
  MaxLength sdk.Int
}
```

let me know what you think @RiccardoM

**Comment by RiccardoM** [comment]
@bragaz I agree these names are more detailed. Can we just use `Nickname`, `DTag` and `Bio` for the field names though? Since they are fields of the `Params` struct I think we can remove the `Limits` and `Policies` suffixes
