### ISSUE TITLE
18+ profiles indicator

### ISSUE THREAD

**Issue by ryuash** [desmos-labs/desmos#621]
## Feature description 

For ui purposes we might not be able to show these type of profiles without giving a warning.

## Implementation proposal

Add a flag indicator that allows user or the owner themselve to flag their profile as being 18+ or rated R

**Comment by RiccardoM** [comment]
I think this can be solved now using the [`x/reports` module](https://docs.desmos.network/developers/modules/reports/overview) that allows users to report an individual. What BigDipper can do is: 
1. create a subspace representing BigDipper itself; 
2. register a [reporting reason](https://docs.desmos.network/developers/modules/reports/concepts#reason) to be used to report 18+ profiles;
3. show a warning when a profile has been reported for that reason, before displaying it inside BigDipper. 

I will close this issue and simply tag here @MonikaCat and @huichiaotsou to see if this can be put inside BigDipper
