### ISSUE TITLE
Duplicate entries in children after post edit

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#63]
The post with ID 44 was edited before. After the edit, children list of the parent post with ID 42 has two `44` there. It should be only one.

http://lcd.morpheus.desmos.network:1317/posts/42

```
{
height: "0",
result: {
id: "42",
parent_id: "0",
message: "DEStroy MOdern Slavery in 2020",
created: "286474",
last_edited: "0",
allows_comments: true,
external_reference: "",
owner: "desmos1jzju74lns6ldhfs9zqt256uuvh0fk98xlzlzaw",
likes: [
{
created: "286699",
owner: "desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u"
}
],
children: [
"43",
"44",
"44"
]
}
}
```
Should we record all changes like FB?

**Comment by bragaz** [comment]
Mmmh, I think we need to check if children's ID is already present by editing the  
```golang
SavePost(ctx sdk.Context, post types.Post)
```
function at line 65, something like `appendIfMissing` we were used to do in commercio, if it was the right approach. What do you think? @RiccardoM, if you want i can take care of this.

**Comment by RiccardoM** [comment]
> What do you think? @RiccardoM, if you want i can take care of this.

Yes, this is the best solution. Please go ahead and create a PR for this

**Comment by RiccardoM** [comment]
@bragaz To speed up the `0.1.1` release I'll take care of this
