### ISSUE TITLE
Limit the number and length of arbitrary data

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#66]
## Context
With #52 we introduced the ability to put arbitrary data inside each post. This is particularly useful to developers when wanting to attach any external data that might be later helpful to a post. 

However, while highly useful, it also might become a problem if some attacker starts using this field to put crazily long data inside it to increase the chain storage enormously. 

## Solution
What I have thought is to limit the **number** of arbitrary data that can be stored per post as well as the **length** of each data stored. The limitations I have thought are:

- **maximum 10 fields** per post 
- **maximum 200 chars** per field

This will lead to at most 2000 bytes-length arbitrary data fields, which IMO will be sufficient for most developers as well as reasonably low to store on chain. 

In the future, if needed, we can increase both limits independently. 

What do you guys think? @kwunyeung @bragaz

**Comment by kwunyeung** [comment]
Yes I think this is more than enough for now.
