### ISSUE TITLE
Update Docs: state sync rpc

### ISSUE THREAD

**Issue by ryuash** [desmos-labs/desmos#674]
Currently the docs say:

```
Set the RPC addresses from where to get the snapshots using the rpc_servers field 
and filling it with two RPCs from this list. These are two of our fullnodes that 
are set up to create periodic snapshots every 500 blocks.
```

But not all the RPCs in this list actually have state sync (to my knowledge).

Best to remove this line or at least add a new folder for rpcs specifically with snapshots included

**Comment by bragaz** [comment]
You're right. I will edit it, thanks @ryuash

**Comment by bragaz** [comment]
Edited 👍
