### ISSUE TITLE
Add support for hex address in chain link

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#685]
## Feature description 

Currently, Desmos doesn't support linking the hex address to the profile. Therefore, the user can't connect their address of Etheruem or other chains, which apply hex address, to the profile.
We should provide the possibility to create the chain link with a hex address.

## Implementation proposal

Implement the Hex address structure for `AddressData` interface.

**Comment by bragaz** [comment]
I agree with this. We should extend the support to ETH as well. Maybe this is worth for an ADR? @RiccardoM

**Comment by RiccardoM** [comment]
Agree this is something we should be supporting

> I agree with this. We should extend the support to ETH as well. Maybe this is worth for an ADR? @RiccardoM

No ADR is required for such a small change. We can just implement it.

**Comment by dadamu** [comment]
Cool, will work on it soon.
