### ISSUE TITLE
Not able to save posts from genesis file during InitGenesis

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#76]
`desmosd` panic with this during `InitGenesis`.

```
panic: unsupported type map
```
It looks like not the issue of the message is too long and can't be saved. I have reduced post id 46 to less than 500 characters but still can't save the states.

The issue should be the `InitGenesis` passing a wrong object to `SavePost` and it gets panic when it gets a `map` instead of a `Post` during `MustMarshalBinaryBare` due to the change of the genesis file structure before for including reactions.

https://github.com/desmos-labs/desmos/blob/521c2e1884eb3d146f66c505fe3b43779435f8d3/x/posts/genesis.go#L39

**Comment by RiccardoM** [comment]
Fixed with 39d1129
