### ISSUE TITLE
Subspace should be a hash value

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#82]
`subspace` in `Post` is better in hash value so that it can be verified by the users by comparing the hash value instead of relying on comparing with a string.

Consider an imposter is trying to build an app and put `subspace` as `C0SMOS` to pretend to be an app discussing things on `COSMOS`.

But I don't have an idea of how the UX can be done to let normal endusers to verify this yet. @RiccardoM  @bragaz please comment.

**Comment by bragaz** [comment]
This makes sense, also because with only strings we can have users writing "deSmOs", "desm0s" and so on..We will provide a better order using hash so I totally agree with implementing this.
I can implement this  right after the media post review is done

**Comment by kwunyeung** [comment]
I one comment in the PR https://github.com/desmos-labs/desmos/pull/84#issuecomment-577027134
