### ISSUE TITLE
Upgrade to Cosmos SDK v0.45.3

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#825]
[`Cosmos SDK v0.45.3`](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.3) is released. `Tendermint Core` is updated to `v0.34.19` From the [`CHANGELOG`](https://github.com/tendermint/tendermint/blob/v0.34.19/CHANGELOG.md#v03417) of `v0.34.17`, it should fix the issue we had during testnet upgrade.

**Comment by bragaz** [comment]
@kwunyeung done already here #823. I'm closing this
