### ISSUE TITLE
Remove terminal dependencies and build desmoscli in wasm

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#9]
There are so many dependencies in the Cosmos SDK which uses Cobra and Viper. These dependencies make the `desmoscli` can't be compiled purely to wasm. We should figure out a way to remove those dependencies to build a standalone wasm binary which can be run on browser and mobile app directly.

**Comment by kwunyeung** [comment]
close #2

**Comment by RiccardoM** [comment]
I personally think that thanks to [Juno](https://github.com/desmos-labs/juno), the upcoming [Stargate update](https://figment.network/resources/cosmos-stargate-upgrade-overview/) (which implements Protobuf) and the work that's being made on the [CosmJs library](https://github.com/CosmWasm/cosmjs) as well as all the other web libraries, we should think if running a full\light node inside a web browser is really what we want. 

I personally think that we should drop this objective as it seems highly undesirable to have such a energy consuming workload on web pages that are used only from a mobile phone or laptop. What do you think @kwunyeung?

**Comment by kwunyeung** [comment]
Yup I also have this thought last couple days.
