### ISSUE TITLE
Implement invariants 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#90]
Currently there are no [invariants](https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/module.go#L92) set for the `posts` module nor the `magpie` module. I really think we should implement those as they allow to check for each block that the state is preserved correctly.

**Comment by RiccardoM** [comment]
Some possible invariants that might be useful to preserve are the following: 

1. Make sure the `LastPostID` is always equals to the greatest `PostID` inserted. 
   This should avoid the reproducing of #63 in the future

2. Make sure that each post reaction refers to an existing post.  
   This should avoid storing invalid reactions. 

3. Make sure each post has a `ParentID` referring to an existing post.  
   This should avoid storing invalid comments.

**Comment by bragaz** [comment]
Also maybe:
Make sure that `pollAnswers` referring to an existing post with poll?

**Comment by RiccardoM** [comment]
If we change how ids are generated (#131), we could change the comments check to be: 

* Make sure that every post comment has a creation date **after** the parent post

**Comment by bragaz** [comment]
We could start implementing invariants after we fixed posts IDs

**Comment by RiccardoM** [comment]
@bragaz Yeah I think that's the way to go. Maybe we can have id fixing into a PR and invariants into another one, both targeting `0.4.0`? Do you think that could be possibile?

**Comment by bragaz** [comment]
This depends on when we decided to roll-out the new testnet.
I think it would be better anyway to target new IDs fixes  to `0.4.0` and the invariants to `0.5.0`.
This should give us the proper time to test them carefully.
But, if you think this should better added into `0.4.0` we can make it.
