### ISSUE TITLE
Replacing goleveldb with boltdb 

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#97]
Tendermint now supports `boltdb`. It has a random indexer and I guess it will give a better performance with large amount of data. We should study if we want our validators to set this as default setting.

**Comment by RiccardoM** [comment]
Are there any bechmark tests of this vs the current database system?

**Comment by kwunyeung** [comment]
Maybe this one worth taking a look.

https://medium.com/@smallnest/go-k-v-databases-benchmark-cd051279ef22

And Oasis is using boltdb.

**Comment by kwunyeung** [comment]
Closed as in favour of using RocksDB which is tracked with #111
